import {
  Barbell,
  Bird,
  BowlFood,
  Bread,
  Cake,
  CalendarBlank,
  Carrot,
  ChefHat,
  ClockCountdown,
  Coffee,
  Cookie,
  CookingPot,
  Drop,
  Egg,
  Fire,
  Fish,
  ForkKnife,
  Hamburger,
  Heart,
  Martini,
  Orange,
  Pizza,
  Popcorn,
  Snowflake,
  SquaresFour,
  Tree,
  WaveSine,
  Wine,
} from '@phosphor-icons/react';
import { PRIMARY_CATEGORIES } from '@/constants/taxonomia';

const phosphorIcons = {
  'Prato Principal': ForkKnife,
  Sobremesa: Cake,
  Entrada: SquaresFour,
  Acompanhamento: BowlFood,
  Salada: Carrot,
  Sopa: CookingPot,
  Lanche: Hamburger,
  Petisco: Popcorn,
  Bebida: Wine,
  'Pão': Bread,
  Molho: Drop,

  Massas: ForkKnife,
  'Arroz & Risotos': BowlFood,
  Frango: Bird,
  'Carne Vermelha': ForkKnife,
  'Peixes & Frutos do Mar': Fish,
  'Tortas Salgadas': SquaresFour,
  'Refogados & Ensopados': CookingPot,
  Bolos: Cake,
  'Tortas Doces': Cake,
  Cheesecakes: Cake,
  'Pudins & Cremes': Egg,
  Mousses: BowlFood,
  Gelados: Snowflake,
  Docinhos: Cake,
  Brownies: Cake,
  Frutas: Orange,
  'Biscoitos & Cookies': Cookie,
  Arroz: BowlFood,
  Feijão: BowlFood,
  Legumes: Carrot,
  Batatas: BowlFood,
  'Farofas & Farinhas': BowlFood,
  Purês: BowlFood,
  'Saladas Verdes': Carrot,
  'Saladas de Grãos': BowlFood,
  'Saladas de Massa': ForkKnife,
  'Saladas de Frutas': Orange,
  Cremes: BowlFood,
  Caldos: CookingPot,
  'Sopas Completas': CookingPot,
  Sanduíches: Hamburger,
  Pizzas: Pizza,
  Tapiocas: SquaresFour,
  'Salgados Assados': SquaresFour,
  'Salgados Fritos': SquaresFour,
  'Wraps & Enrolados': SquaresFour,
  Bolinhos: SquaresFour,
  'Petiscos Quentes': Fire,
  'Petiscos Frios': Snowflake,
  Sucos: Orange,
  Vitaminas: Martini,
  Drinks: Wine,
  'Chás & Infusões': Coffee,
  Cafés: Coffee,
  Shakes: Martini,
  'Pães Caseiros': Bread,
  'Pão de Queijo': Bread,
  Focaccias: Bread,
  Brioches: Bread,
  'Massa Folhada': Bread,
  'Molhos Quentes': Fire,
  'Molhos Frios': Snowflake,
  'Molhos Doces': Drop,

  'Café da Manhã': Coffee,
  Brunch: BowlFood,
  Almoço: ForkKnife,
  'Lanche da Tarde': Coffee,
  Jantar: ForkKnife,
  Ceia: CalendarBlank,

  Vegetariana: Carrot,
  Vegana: Carrot,
  'Sem Glúten': SquaresFour,
  'Sem Lactose': Drop,
  'Low Carb': Barbell,
  Fit: Barbell,
  Cetogênica: Barbell,
  'Zero Açúcar': Drop,
  'High Protein': Barbell,

  'Carne Bovina': ForkKnife,
  'Carne Moída': ForkKnife,
  'Carne Suína': ForkKnife,
  Peixe: Fish,
  Salmão: Fish,
  Bacalhau: Fish,
  Camarão: Fish,
  Ovos: Egg,
  Queijo: BowlFood,
  Macarrão: ForkKnife,
  Batata: BowlFood,
  Mandioca: BowlFood,
  Milho: Carrot,
  Chocolate: Cake,
  'Leite Condensado': Drop,
  Coco: BowlFood,
  Banana: Orange,
  Maçã: Orange,
  Morango: Orange,
  Limão: Orange,
  Maracujá: Orange,
  Laranja: Orange,
  Abobrinha: Carrot,
  Berinjela: Carrot,
  Tomate: Carrot,
  Cenoura: Carrot,
  Abóbora: Carrot,

  Páscoa: Egg,
  'Dia das Mães': Heart,
  'Dia dos Namorados': Heart,
  'Dia dos Pais': Heart,
  Natal: Tree,
  'Ano Novo': CalendarBlank,
  'Festas de Fim de Ano': Tree,
  Aniversário: Cake,
  Inverno: Snowflake,
  'Receitas em 30 min': ClockCountdown,
  'Poucos Ingredientes': SquaresFour,
  Econômica: SquaresFour,
  'Para Congelar': Snowflake,
  'Preparar com Antecedência': ClockCountdown,
  'Comfort Food': Heart,
  'Receita de Vó': Heart,
  'Para Crianças': Popcorn,
  'Para Dois': Heart,
  'Receita Clássica': ChefHat,
};

const emojiIcons = {
  'Arroz & Risotos': '🍚',
  Frango: '🍗',
  'Peixes & Frutos do Mar': '🐟',
  Bolos: '🎂',
  'Tortas Doces': '🥧',
  Cheesecakes: '🍰',
  'Pudins & Cremes': '🍮',
  Mousses: '🍨',
  Gelados: '🍦',
  Docinhos: '🍬',
  Brownies: '🍫',
  Frutas: '🍓',
  'Biscoitos & Cookies': '🍪',
  Arroz: '🍚',
  Feijão: '🫘',
  Legumes: '🥕',
  Batatas: '🥔',
  Purês: '🥣',
  'Saladas Verdes': '🥗',
  'Saladas de Grãos': '🥗',
  'Saladas de Massa': '🥗',
  'Saladas de Frutas': '🍓',
  Cremes: '🥣',
  Caldos: '🍲',
  'Sopas Completas': '🍲',
  Sanduíches: '🥪',
  Pizzas: '🍕',
  Tapiocas: '🫓',
  'Salgados Assados': '🥐',
  'Salgados Fritos': '🍤',
  'Wraps & Enrolados': '🌯',
  Bolinhos: '🧆',
  'Petiscos Quentes': '🍢',
  'Petiscos Frios': '🧀',
  Sucos: '🧃',
  Vitaminas: '🥤',
  Drinks: '🍹',
  'Chás & Infusões': '🫖',
  Cafés: '☕',
  Shakes: '🥤',
  'Pães Caseiros': '🍞',
  'Pão de Queijo': '🧀',
  Focaccias: '🍞',
  Brioches: '🥐',
  'Massa Folhada': '🥐',
  'Molhos Quentes': '🌶️',
  'Molhos Frios': '🧊',
  'Molhos Doces': '🍯',

  Brasileira: '🇧🇷',
  Mineira: '⛰️',
  Capixaba: '🐟',
  Nordestina: '🌵',
  Italiana: '🇮🇹',
  Japonesa: '🇯🇵',
  Chinesa: '🇨🇳',
  Mexicana: '🇲🇽',
  Francesa: '🇫🇷',
  Espanhola: '🇪🇸',
  Grega: '🇬🇷',
  Inglesa: '🇬🇧',
  Árabe: '🧆',
  Americana: '🇺🇸',
  Portuguesa: '🇵🇹',
  Indiana: '🇮🇳',
  Mediterrânea: '🌊',
  Tailandesa: '🇹🇭',

  'Air Fryer': '🍟',
  Forno: '🍞',
  Fogão: '♨️',
  'Panela de Pressão': '🍲',
  'Micro-ondas': '📡',
  Churrasco: '🥩',
  'Sem Forno': '🚫🔥',
  Liquidificador: '🥤',
  Fritura: '🍤',
  'Slow Cooker': '🍲',
  'Sous Vide': '💧',

  Vegetariana: '🥕',
  Vegana: '🌿',
  'Sem Glúten': '🚫🌾',
  'Sem Lactose': '🚫🥛',
  Fit: '💪',
  'Zero Açúcar': '🚫🍬',
  'High Protein': '💪',

  'Carne Bovina': '🥩',
  'Carne Moída': '🥩',
  'Carne Suína': '🥓',
  Peixe: '🐟',
  Salmão: '🐟',
  Bacalhau: '🐟',
  Camarão: '🦐',
  Ovos: '🥚',
  Queijo: '🧀',
  Macarrão: '🍝',
  Batata: '🥔',
  Milho: '🌽',
  Chocolate: '🍫',
  Coco: '🥥',
  Banana: '🍌',
  Maçã: '🍎',
  Morango: '🍓',
  Limão: '🍋',
  Maracujá: '🥭',
  Laranja: '🍊',
  Berinjela: '🍆',
  Tomate: '🍅',
  Cenoura: '🥕',
  Abóbora: '🎃',

  'Happy Hour': '🍸',
  Verão: '☀️',
  'Festa Junina': '🎉',
  Páscoa: '🥚',
  Natal: '🎄',
  Aniversário: '🎂',
  Inverno: '❄️',
  'Receitas em 30 min': '⏱️',
  Econômica: '💸',
  'Para Congelar': '🧊',
  'Preparar com Antecedência': '⏳',
  'Comfort Food': '🤎',
  'Receita de Vó': '👵',
  'Para Crianças': '🧒',
  'Para Dois': '💞',
  'Receita Clássica': '⭐',
};

export function getCategoryIconSpec(name) {
  if (emojiIcons[name]) {
    return { type: 'emoji', value: emojiIcons[name] };
  }

  if (phosphorIcons[name]) {
    return { type: 'phosphor', value: phosphorIcons[name] };
  }

  if (PRIMARY_CATEGORIES.includes(name)) {
    return { type: 'phosphor', value: phosphorIcons[name] || SquaresFour };
  }

  return { type: 'phosphor', value: SquaresFour };
}
