import type { Recommendation, ReviewKind } from '@/lib/content';
import type { Locale } from '@/lib/i18n/locales';

// Textos do corpo do artigo que não são conteúdo editorial: selo do tipo, veredito e nota, ficha do
// produto, bloco de vídeo e legenda da imagem. A sidebar e o dock têm os deles em sidebarCopy.ts.
// O código de indicação da SHEIN é da SHEIN Brasil e fora do PT o chip diz isso, com os termos da
// página da loja (couponTranslations.ts).
export type ArticleCopy = {
  kindLabel: Record<ReviewKind, string>;
  verdictTitle: string;
  editorialNoteTitle: string;
  ratingLabel: (stars: string) => string;
  recommendation: Record<Recommendation, string>;
  approvedSeal: string;
  scoreTitle: string;
  verdictHeading: string;
  rated: string;
  strengths: string;
  cautions: string;
  worthIt: string;
  codeChip: {
    coupon: (code: string) => string;
    reward: (code: string) => string;
    referral: (code: string, brand: string) => string;
  };
  heroCaption: (stars: string) => string;
  finalVerdictLink: string;
  productSheet: string;
  productSheetOpen: string;
  productSheetClose: string;
  productSheetCaption: string;
  productSheetLink: string;
  relatedVideo: string;
  watchOnYoutube: string;
  openVideoPage: string;
};

const articleCopy: Record<Locale, ArticleCopy> = {
  pt: {
    kindLabel: { produto: 'Review de produto', guia: 'Guia', editorial: 'Editorial' },
    verdictTitle: 'Veredito da Cecília',
    editorialNoteTitle: 'Nota editorial',
    ratingLabel: (stars) => `Avaliação ${stars} de 5 estrelas`,
    recommendation: { recomendo: '✓ Recomendo', 'com ressalvas': 'Com ressalvas', 'não recomendo': 'Não recomendo' },
    approvedSeal: 'Aprovado pela Cecília',
    scoreTitle: 'Nota da Cecília',
    verdictHeading: 'Veredito',
    rated: 'Avaliado',
    strengths: 'Pontos fortes',
    cautions: 'Pontos de atenção',
    worthIt: 'Vale a pena',
    codeChip: {
      coupon: (code) => `Cupom ${code}`,
      reward: (code) => `Código de recompensa ${code}`,
      referral: (code, brand) => `Código de indicação ${brand} ${code}`,
    },
    heroCaption: (stars) => `Imagem do produto avaliado com nota ${stars} de 5.`,
    finalVerdictLink: 'Copiar link do veredito final',
    productSheet: 'Ficha do produto',
    productSheetOpen: 'Abrir',
    productSheetClose: 'Fechar',
    productSheetCaption: 'Ficha técnica do produto avaliado',
    productSheetLink: 'Copiar link da ficha do produto',
    relatedVideo: 'Vídeo relacionado',
    watchOnYoutube: 'Assista ao vídeo completo no YouTube',
    openVideoPage: 'Abrir a página dedicada ao vídeo',
  },
  en: {
    kindLabel: { produto: 'Product review', guia: 'Guide', editorial: 'Editorial' },
    verdictTitle: "Cecília's verdict",
    editorialNoteTitle: 'Editorial note',
    ratingLabel: (stars) => `Rated ${stars} out of 5 stars`,
    recommendation: { recomendo: '✓ Recommended', 'com ressalvas': 'With reservations', 'não recomendo': 'Not recommended' },
    approvedSeal: 'Approved by Cecília',
    scoreTitle: "Cecília's score",
    verdictHeading: 'Verdict',
    rated: 'Rated',
    strengths: 'Strengths',
    cautions: 'Things to watch',
    worthIt: 'Worth it',
    codeChip: {
      coupon: (code) => `Discount code ${code}`,
      reward: (code) => `Reward Code ${code}`,
      referral: (code, brand) => `${brand} Brazil referral code ${code}`,
    },
    heroCaption: (stars) => `Product image, rated ${stars} out of 5.`,
    finalVerdictLink: 'Copy link to the final verdict',
    productSheet: 'Product details',
    productSheetOpen: 'Open',
    productSheetClose: 'Close',
    productSheetCaption: 'Technical details of the reviewed product',
    productSheetLink: 'Copy link to the product details',
    relatedVideo: 'Related video',
    watchOnYoutube: 'Watch the full video on YouTube',
    openVideoPage: 'Open the dedicated video page',
  },
  es: {
    kindLabel: { produto: 'Reseña de producto', guia: 'Guía', editorial: 'Editorial' },
    verdictTitle: 'Veredicto de Cecília',
    editorialNoteTitle: 'Nota editorial',
    ratingLabel: (stars) => `Valoración ${stars} de 5 estrellas`,
    recommendation: { recomendo: '✓ Lo recomiendo', 'com ressalvas': 'Con reservas', 'não recomendo': 'No lo recomiendo' },
    approvedSeal: 'Aprobado por Cecília',
    scoreTitle: 'Nota de Cecília',
    verdictHeading: 'Veredicto',
    rated: 'Valorado',
    strengths: 'Puntos fuertes',
    cautions: 'Puntos a tener en cuenta',
    worthIt: 'Vale la pena',
    codeChip: {
      coupon: (code) => `Código de descuento ${code}`,
      reward: (code) => `Código de recompensa ${code}`,
      referral: (code, brand) => `Código de referido de ${brand} Brasil ${code}`,
    },
    heroCaption: (stars) => `Imagen del producto valorado con nota ${stars} de 5.`,
    finalVerdictLink: 'Copiar enlace del veredicto final',
    productSheet: 'Ficha del producto',
    productSheetOpen: 'Abrir',
    productSheetClose: 'Cerrar',
    productSheetCaption: 'Ficha técnica del producto analizado',
    productSheetLink: 'Copiar enlace de la ficha del producto',
    relatedVideo: 'Vídeo relacionado',
    watchOnYoutube: 'Mira el vídeo completo en YouTube',
    openVideoPage: 'Abrir la página dedicada al vídeo',
  },
  fr: {
    kindLabel: { produto: 'Test de produit', guia: 'Guide', editorial: 'Éditorial' },
    verdictTitle: 'Le verdict de Cecília',
    editorialNoteTitle: 'Note de la rédaction',
    ratingLabel: (stars) => `Note de ${stars} sur 5 étoiles`,
    recommendation: { recomendo: '✓ Je recommande', 'com ressalvas': 'Avec réserves', 'não recomendo': 'Je ne recommande pas' },
    approvedSeal: 'Approuvé par Cecília',
    scoreTitle: 'Note de Cecília',
    verdictHeading: 'Verdict',
    rated: 'Évalué',
    strengths: 'Points forts',
    cautions: 'Points de vigilance',
    worthIt: 'Ça vaut le coup',
    codeChip: {
      coupon: (code) => `Code promo ${code}`,
      reward: (code) => `Code récompense ${code}`,
      referral: (code, brand) => `Code de parrainage ${brand} Brésil ${code}`,
    },
    heroCaption: (stars) => `Image du produit évalué, note de ${stars} sur 5.`,
    finalVerdictLink: 'Copier le lien du verdict final',
    productSheet: 'Fiche produit',
    productSheetOpen: 'Ouvrir',
    productSheetClose: 'Fermer',
    productSheetCaption: 'Fiche technique du produit évalué',
    productSheetLink: 'Copier le lien de la fiche produit',
    relatedVideo: 'Vidéo associée',
    watchOnYoutube: 'Regardez la vidéo complète sur YouTube',
    openVideoPage: 'Ouvrir la page dédiée à la vidéo',
  },
  de: {
    kindLabel: { produto: 'Produkttest', guia: 'Ratgeber', editorial: 'Redaktionell' },
    verdictTitle: 'Cecílias Urteil',
    editorialNoteTitle: 'Redaktioneller Hinweis',
    ratingLabel: (stars) => `Bewertung ${stars} von 5 Sternen`,
    recommendation: { recomendo: '✓ Empfehlenswert', 'com ressalvas': 'Mit Einschränkungen', 'não recomendo': 'Nicht empfehlenswert' },
    approvedSeal: 'Von Cecília empfohlen',
    scoreTitle: 'Cecílias Note',
    verdictHeading: 'Urteil',
    rated: 'Bewertet',
    strengths: 'Stärken',
    cautions: 'Worauf man achten sollte',
    worthIt: 'Lohnt sich',
    codeChip: {
      coupon: (code) => `Rabattcode ${code}`,
      reward: (code) => `Reward Code ${code}`,
      referral: (code, brand) => `Empfehlungscode von ${brand} Brasilien ${code}`,
    },
    heroCaption: (stars) => `Bild des bewerteten Produkts, Note ${stars} von 5.`,
    finalVerdictLink: 'Link zum abschließenden Urteil kopieren',
    productSheet: 'Produktdaten',
    productSheetOpen: 'Öffnen',
    productSheetClose: 'Schließen',
    productSheetCaption: 'Technische Daten des bewerteten Produkts',
    productSheetLink: 'Link zu den Produktdaten kopieren',
    relatedVideo: 'Passendes Video',
    watchOnYoutube: 'Das ganze Video auf YouTube ansehen',
    openVideoPage: 'Seite zum Video öffnen',
  },
  it: {
    kindLabel: { produto: 'Recensione di prodotto', guia: 'Guida', editorial: 'Editoriale' },
    verdictTitle: 'Il verdetto di Cecília',
    editorialNoteTitle: 'Nota editoriale',
    ratingLabel: (stars) => `Valutazione ${stars} su 5 stelle`,
    recommendation: { recomendo: '✓ Lo consiglio', 'com ressalvas': 'Con riserve', 'não recomendo': 'Non lo consiglio' },
    approvedSeal: 'Approvato da Cecília',
    scoreTitle: 'Voto di Cecília',
    verdictHeading: 'Verdetto',
    rated: 'Valutato',
    strengths: 'Punti di forza',
    cautions: 'Punti di attenzione',
    worthIt: 'Ne vale la pena',
    codeChip: {
      coupon: (code) => `Codice sconto ${code}`,
      reward: (code) => `Codice ricompensa ${code}`,
      referral: (code, brand) => `Codice invito ${brand} Brasile ${code}`,
    },
    heroCaption: (stars) => `Immagine del prodotto valutato, voto ${stars} su 5.`,
    finalVerdictLink: 'Copia il link del verdetto finale',
    productSheet: 'Scheda del prodotto',
    productSheetOpen: 'Apri',
    productSheetClose: 'Chiudi',
    productSheetCaption: 'Scheda tecnica del prodotto valutato',
    productSheetLink: 'Copia il link della scheda del prodotto',
    relatedVideo: 'Video correlato',
    watchOnYoutube: 'Guarda il video completo su YouTube',
    openVideoPage: 'Apri la pagina dedicata al video',
  },
  ko: {
    kindLabel: { produto: '제품 리뷰', guia: '가이드', editorial: '에디토리얼' },
    verdictTitle: 'Cecília의 평가',
    editorialNoteTitle: '편집 노트',
    ratingLabel: (stars) => `5점 만점에 ${stars}점`,
    recommendation: { recomendo: '✓ 추천', 'com ressalvas': '조건부 추천', 'não recomendo': '비추천' },
    approvedSeal: 'Cecília 인증',
    scoreTitle: 'Cecília의 점수',
    verdictHeading: '평가',
    rated: '평가 완료',
    strengths: '장점',
    cautions: '참고할 점',
    worthIt: '살 만해요',
    codeChip: {
      coupon: (code) => `할인 코드 ${code}`,
      reward: (code) => `리워드 코드 ${code}`,
      referral: (code, brand) => `${brand} 브라질 추천 코드 ${code}`,
    },
    heroCaption: (stars) => `5점 만점에 ${stars}점으로 평가한 제품 이미지.`,
    finalVerdictLink: '최종 평가 링크 복사',
    productSheet: '제품 정보',
    productSheetOpen: '열기',
    productSheetClose: '닫기',
    productSheetCaption: '평가한 제품의 상세 사양',
    productSheetLink: '제품 정보 링크 복사',
    relatedVideo: '관련 영상',
    watchOnYoutube: 'YouTube에서 전체 영상 보기',
    openVideoPage: '영상 전용 페이지 열기',
  },
  ja: {
    kindLabel: { produto: '製品レビュー', guia: 'ガイド', editorial: 'エディトリアル' },
    verdictTitle: 'Cecília の評価',
    editorialNoteTitle: '編集部より',
    ratingLabel: (stars) => `5つ星中${stars}の評価`,
    recommendation: { recomendo: '✓ おすすめ', 'com ressalvas': '条件付きでおすすめ', 'não recomendo': 'おすすめしません' },
    approvedSeal: 'Cecília 認定',
    scoreTitle: 'Cecília のスコア',
    verdictHeading: '評価',
    rated: '評価済み',
    strengths: '良い点',
    cautions: '気になる点',
    worthIt: '買う価値あり',
    codeChip: {
      coupon: (code) => `割引コード ${code}`,
      reward: (code) => `リワードコード ${code}`,
      referral: (code, brand) => `${brand} ブラジルの紹介コード ${code}`,
    },
    heroCaption: (stars) => `5点満点中${stars}点と評価した製品の画像。`,
    finalVerdictLink: '最終評価のリンクをコピー',
    productSheet: '製品情報',
    productSheetOpen: '開く',
    productSheetClose: '閉じる',
    productSheetCaption: '評価した製品の仕様',
    productSheetLink: '製品情報のリンクをコピー',
    relatedVideo: '関連動画',
    watchOnYoutube: 'YouTube で動画の全編を見る',
    openVideoPage: '動画専用ページを開く',
  },
  'zh-hant': {
    kindLabel: { produto: '產品評測', guia: '指南', editorial: '編輯專題' },
    verdictTitle: 'Cecília 的評價',
    editorialNoteTitle: '編輯備註',
    ratingLabel: (stars) => `評分 ${stars} 分（滿分 5 星）`,
    recommendation: { recomendo: '✓ 推薦', 'com ressalvas': '有條件推薦', 'não recomendo': '不推薦' },
    approvedSeal: 'Cecília 認證',
    scoreTitle: 'Cecília 的評分',
    verdictHeading: '評價',
    rated: '已評分',
    strengths: '優點',
    cautions: '注意事項',
    worthIt: '值得入手',
    codeChip: {
      coupon: (code) => `優惠碼 ${code}`,
      reward: (code) => `獎勵碼 ${code}`,
      referral: (code, brand) => `${brand} 巴西站推薦碼 ${code}`,
    },
    heroCaption: (stars) => `評分 ${stars} 分（滿分 5 分）的產品圖片。`,
    finalVerdictLink: '複製最終評價連結',
    productSheet: '產品資訊',
    productSheetOpen: '展開',
    productSheetClose: '收合',
    productSheetCaption: '所評測產品的規格資料',
    productSheetLink: '複製產品資訊連結',
    relatedVideo: '相關影片',
    watchOnYoutube: '在 YouTube 觀看完整影片',
    openVideoPage: '開啟影片專頁',
  },
  'zh-hans': {
    kindLabel: { produto: '产品评测', guia: '指南', editorial: '编辑专题' },
    verdictTitle: 'Cecília 的评价',
    editorialNoteTitle: '编辑备注',
    ratingLabel: (stars) => `评分 ${stars} 分（满分 5 星）`,
    recommendation: { recomendo: '✓ 推荐', 'com ressalvas': '有条件推荐', 'não recomendo': '不推荐' },
    approvedSeal: 'Cecília 认证',
    scoreTitle: 'Cecília 的评分',
    verdictHeading: '评价',
    rated: '已评分',
    strengths: '优点',
    cautions: '注意事项',
    worthIt: '值得入手',
    codeChip: {
      coupon: (code) => `优惠码 ${code}`,
      reward: (code) => `奖励码 ${code}`,
      referral: (code, brand) => `${brand} 巴西站推荐码 ${code}`,
    },
    heroCaption: (stars) => `评分 ${stars} 分（满分 5 分）的产品图片。`,
    finalVerdictLink: '复制最终评价链接',
    productSheet: '产品信息',
    productSheetOpen: '展开',
    productSheetClose: '收起',
    productSheetCaption: '所评测产品的规格资料',
    productSheetLink: '复制产品信息链接',
    relatedVideo: '相关视频',
    watchOnYoutube: '在 YouTube 观看完整视频',
    openVideoPage: '打开视频专页',
  },
};

export function getArticleCopy(locale: Locale): ArticleCopy {
  return articleCopy[locale];
}
