import type { Locale } from '@/lib/i18n/locales';

// O francês pede espaço antes de : ; ? ! e %, e ele não pode quebrar a linha.
const NBSP = ' ';

// Textos da galeria de fotos e vídeos do fim do artigo (ReviewGallerySection). O título de vídeo
// sem nome vem de articleCopy.ts.
export type GalleryCopy = {
  eyebrow: string;
  heading: string;
  tabPhotos: string;
  tabVideos: string;
  photoGallery: string;
  enlargeImage: (position: number) => string;
  enlarge: string;
  photoAlt: string;
  previousPhotos: string;
  nextPhotos: string;
  swipePhotos: (count: number) => string;
  videoCarousel: string;
  video: string;
  previousVideos: string;
  nextVideos: string;
  swipeVideos: (count: number) => string;
  closeImage: string;
  previousImage: string;
  nextImage: string;
  imageAlt: string;
  // Imagens dentro das seções do artigo (ReviewInlineImage).
  enlargeNamed: (alt: string) => string;
  enlargedImage: (position: number, total: number) => string;
  imageCarousel: string;
};

const galleryCopy: Record<Locale, GalleryCopy> = {
  pt: {
    eyebrow: 'Galeria',
    heading: 'Fotos e vídeos',
    tabPhotos: 'Fotos',
    tabVideos: 'Vídeos',
    photoGallery: 'Galeria de fotos',
    enlargeImage: (position) => `Ampliar imagem ${position}`,
    enlarge: 'Ampliar',
    photoAlt: 'Foto da galeria',
    previousPhotos: 'Fotos anteriores',
    nextPhotos: 'Próximas fotos',
    swipePhotos: (count) => `Arraste para ver mais · ${count} fotos`,
    videoCarousel: 'Carrossel de vídeos',
    video: 'Vídeo',
    previousVideos: 'Vídeos anteriores',
    nextVideos: 'Próximos vídeos',
    swipeVideos: (count) => `Arraste para ver mais · ${count} vídeos`,
    closeImage: 'Fechar imagem ampliada',
    previousImage: 'Imagem anterior',
    nextImage: 'Próxima imagem',
    imageAlt: 'Imagem da galeria',
    enlargeNamed: (alt) => `Ampliar imagem: ${alt}`,
    enlargedImage: (position, total) => `Imagem ampliada ${position} de ${total}`,
    imageCarousel: 'Carrossel de imagens',
  },
  en: {
    eyebrow: 'Gallery',
    heading: 'Photos and videos',
    tabPhotos: 'Photos',
    tabVideos: 'Videos',
    photoGallery: 'Photo gallery',
    enlargeImage: (position) => `Enlarge image ${position}`,
    enlarge: 'Enlarge',
    photoAlt: 'Gallery photo',
    previousPhotos: 'Previous photos',
    nextPhotos: 'Next photos',
    swipePhotos: (count) => `Swipe to see more · ${count} photos`,
    videoCarousel: 'Video carousel',
    video: 'Video',
    previousVideos: 'Previous videos',
    nextVideos: 'Next videos',
    swipeVideos: (count) => `Swipe to see more · ${count} videos`,
    closeImage: 'Close enlarged image',
    previousImage: 'Previous image',
    nextImage: 'Next image',
    imageAlt: 'Gallery image',
    enlargeNamed: (alt) => `Enlarge image: ${alt}`,
    enlargedImage: (position, total) => `Enlarged image ${position} of ${total}`,
    imageCarousel: 'Image carousel',
  },
  es: {
    eyebrow: 'Galería',
    heading: 'Fotos y vídeos',
    tabPhotos: 'Fotos',
    tabVideos: 'Vídeos',
    photoGallery: 'Galería de fotos',
    enlargeImage: (position) => `Ampliar imagen ${position}`,
    enlarge: 'Ampliar',
    photoAlt: 'Foto de la galería',
    previousPhotos: 'Fotos anteriores',
    nextPhotos: 'Fotos siguientes',
    swipePhotos: (count) => `Desliza para ver más · ${count} fotos`,
    videoCarousel: 'Carrusel de vídeos',
    video: 'Vídeo',
    previousVideos: 'Vídeos anteriores',
    nextVideos: 'Vídeos siguientes',
    swipeVideos: (count) => `Desliza para ver más · ${count} vídeos`,
    closeImage: 'Cerrar imagen ampliada',
    previousImage: 'Imagen anterior',
    nextImage: 'Imagen siguiente',
    imageAlt: 'Imagen de la galería',
    enlargeNamed: (alt) => `Ampliar imagen: ${alt}`,
    enlargedImage: (position, total) => `Imagen ampliada ${position} de ${total}`,
    imageCarousel: 'Carrusel de imágenes',
  },
  fr: {
    eyebrow: 'Galerie',
    heading: 'Photos et vidéos',
    tabPhotos: 'Photos',
    tabVideos: 'Vidéos',
    photoGallery: 'Galerie de photos',
    enlargeImage: (position) => `Agrandir l’image ${position}`,
    enlarge: 'Agrandir',
    photoAlt: 'Photo de la galerie',
    previousPhotos: 'Photos précédentes',
    nextPhotos: 'Photos suivantes',
    swipePhotos: (count) => `Faites défiler pour en voir plus · ${count} photos`,
    videoCarousel: 'Carrousel de vidéos',
    video: 'Vidéo',
    previousVideos: 'Vidéos précédentes',
    nextVideos: 'Vidéos suivantes',
    swipeVideos: (count) => `Faites défiler pour en voir plus · ${count} vidéos`,
    closeImage: 'Fermer l’image agrandie',
    previousImage: 'Image précédente',
    nextImage: 'Image suivante',
    imageAlt: 'Image de la galerie',
    enlargeNamed: (alt) => `Agrandir l’image${NBSP}: ${alt}`,
    enlargedImage: (position, total) => `Image agrandie ${position} sur ${total}`,
    imageCarousel: 'Carrousel d’images',
  },
  de: {
    eyebrow: 'Galerie',
    heading: 'Fotos und Videos',
    tabPhotos: 'Fotos',
    tabVideos: 'Videos',
    photoGallery: 'Fotogalerie',
    enlargeImage: (position) => `Bild ${position} vergrößern`,
    enlarge: 'Vergrößern',
    photoAlt: 'Galeriefoto',
    previousPhotos: 'Vorherige Fotos',
    nextPhotos: 'Nächste Fotos',
    swipePhotos: (count) => `Wischen für mehr · ${count} Fotos`,
    videoCarousel: 'Videokarussell',
    video: 'Video',
    previousVideos: 'Vorherige Videos',
    nextVideos: 'Nächste Videos',
    swipeVideos: (count) => `Wischen für mehr · ${count} Videos`,
    closeImage: 'Vergrößertes Bild schließen',
    previousImage: 'Vorheriges Bild',
    nextImage: 'Nächstes Bild',
    imageAlt: 'Galeriebild',
    enlargeNamed: (alt) => `Bild vergrößern: ${alt}`,
    enlargedImage: (position, total) => `Vergrößertes Bild ${position} von ${total}`,
    imageCarousel: 'Bilderkarussell',
  },
  it: {
    eyebrow: 'Galleria',
    heading: 'Foto e video',
    tabPhotos: 'Foto',
    tabVideos: 'Video',
    photoGallery: 'Galleria di foto',
    enlargeImage: (position) => `Ingrandisci l’immagine ${position}`,
    enlarge: 'Ingrandisci',
    photoAlt: 'Foto della galleria',
    previousPhotos: 'Foto precedenti',
    nextPhotos: 'Foto successive',
    swipePhotos: (count) => `Scorri per vedere altro · ${count} foto`,
    videoCarousel: 'Carosello di video',
    video: 'Video',
    previousVideos: 'Video precedenti',
    nextVideos: 'Video successivi',
    swipeVideos: (count) => `Scorri per vedere altro · ${count} video`,
    closeImage: 'Chiudi l’immagine ingrandita',
    previousImage: 'Immagine precedente',
    nextImage: 'Immagine successiva',
    imageAlt: 'Immagine della galleria',
    enlargeNamed: (alt) => `Ingrandisci l’immagine: ${alt}`,
    enlargedImage: (position, total) => `Immagine ingrandita ${position} di ${total}`,
    imageCarousel: 'Carosello di immagini',
  },
  ko: {
    eyebrow: '갤러리',
    heading: '사진과 영상',
    tabPhotos: '사진',
    tabVideos: '영상',
    photoGallery: '사진 갤러리',
    enlargeImage: (position) => `이미지 ${position} 확대`,
    enlarge: '확대',
    photoAlt: '갤러리 사진',
    previousPhotos: '이전 사진',
    nextPhotos: '다음 사진',
    swipePhotos: (count) => `밀어서 더 보기 · 사진 ${count}장`,
    videoCarousel: '영상 캐러셀',
    video: '영상',
    previousVideos: '이전 영상',
    nextVideos: '다음 영상',
    swipeVideos: (count) => `밀어서 더 보기 · 영상 ${count}개`,
    closeImage: '확대한 이미지 닫기',
    previousImage: '이전 이미지',
    nextImage: '다음 이미지',
    imageAlt: '갤러리 이미지',
    enlargeNamed: (alt) => `이미지 확대: ${alt}`,
    enlargedImage: (position, total) => `확대한 이미지 ${position}/${total}`,
    imageCarousel: '이미지 캐러셀',
  },
  ja: {
    eyebrow: 'ギャラリー',
    heading: '写真と動画',
    tabPhotos: '写真',
    tabVideos: '動画',
    photoGallery: '写真ギャラリー',
    enlargeImage: (position) => `画像${position}を拡大`,
    enlarge: '拡大',
    photoAlt: 'ギャラリーの写真',
    previousPhotos: '前の写真',
    nextPhotos: '次の写真',
    swipePhotos: (count) => `スワイプしてもっと見る · 写真${count}枚`,
    videoCarousel: '動画カルーセル',
    video: '動画',
    previousVideos: '前の動画',
    nextVideos: '次の動画',
    swipeVideos: (count) => `スワイプしてもっと見る · 動画${count}本`,
    closeImage: '拡大画像を閉じる',
    previousImage: '前の画像',
    nextImage: '次の画像',
    imageAlt: 'ギャラリーの画像',
    enlargeNamed: (alt) => `画像を拡大：${alt}`,
    enlargedImage: (position, total) => `拡大画像 ${position}/${total}`,
    imageCarousel: '画像カルーセル',
  },
  'zh-hant': {
    eyebrow: '圖庫',
    heading: '照片與影片',
    tabPhotos: '照片',
    tabVideos: '影片',
    photoGallery: '照片圖庫',
    enlargeImage: (position) => `放大圖片 ${position}`,
    enlarge: '放大',
    photoAlt: '圖庫照片',
    previousPhotos: '上一組照片',
    nextPhotos: '下一組照片',
    swipePhotos: (count) => `滑動查看更多 · 共 ${count} 張照片`,
    videoCarousel: '影片輪播',
    video: '影片',
    previousVideos: '上一組影片',
    nextVideos: '下一組影片',
    swipeVideos: (count) => `滑動查看更多 · 共 ${count} 部影片`,
    closeImage: '關閉放大圖片',
    previousImage: '上一張圖片',
    nextImage: '下一張圖片',
    imageAlt: '圖庫圖片',
    enlargeNamed: (alt) => `放大圖片：${alt}`,
    enlargedImage: (position, total) => `放大圖片 ${position}/${total}`,
    imageCarousel: '圖片輪播',
  },
  'zh-hans': {
    eyebrow: '图库',
    heading: '照片与视频',
    tabPhotos: '照片',
    tabVideos: '视频',
    photoGallery: '照片图库',
    enlargeImage: (position) => `放大图片 ${position}`,
    enlarge: '放大',
    photoAlt: '图库照片',
    previousPhotos: '上一组照片',
    nextPhotos: '下一组照片',
    swipePhotos: (count) => `滑动查看更多 · 共 ${count} 张照片`,
    videoCarousel: '视频轮播',
    video: '视频',
    previousVideos: '上一组视频',
    nextVideos: '下一组视频',
    swipeVideos: (count) => `滑动查看更多 · 共 ${count} 个视频`,
    closeImage: '关闭放大图片',
    previousImage: '上一张图片',
    nextImage: '下一张图片',
    imageAlt: '图库图片',
    enlargeNamed: (alt) => `放大图片：${alt}`,
    enlargedImage: (position, total) => `放大图片 ${position}/${total}`,
    imageCarousel: '图片轮播',
  },
};

export function getGalleryCopy(locale: Locale): GalleryCopy {
  return galleryCopy[locale];
}
