import type { Locale } from '@/lib/i18n/locales';

// O francês pede espaço antes de : ; ? e %, e ele não pode quebrar a linha.
const NBSP = '\u00a0';

// Textos da página de cupons da YesStyle nos 10 idiomas. {code}, {newDiscount}, {returningDiscount}
// e {promoCode} são preenchidos com os dados de data/coupons/yesstyle.json.
export type PageCopy = {
  locale: Locale;
  language: string;
  homeLabel: string;
  couponsLabel: string;
  category: string;
  titleTemplate: string;
  descriptionTemplate: string;
  introTemplate: string;
  copyAriaPromoTemplate: string;
  visit: string;
  rewardCodeLabel: string;
  rewardFieldNote: string;
  firstOrderLabel: string;
  nextOrdersLabel: string;
  promosSectionTitle: string;
  promosIntroTemplate: string;
  emptyPromosNoticeTemplate: string;
  emptyPromosSubtextTemplate: string;
  proofLabel: string;
  validityUnconfirmed: string;
  regionUnconfirmed: string;
  freeShippingLabel: string;
  promoLabels: { validity: string; region: string };
  tierTemplate: string;
  noMinimumLabel: string;
  membersOnlyLabel: string;
  allRegionsLabel: string;
  policyTitle: string;
  // Respostas aos rótulos das regras da página de loja: Vale para, Junta com outras promoções?,
  // Validade e Frete.
  policyRules: { eligible: string; combinable: string; validity: string; shipping: string };
  instructionsTitleTemplate: string;
  instructionsTemplates: string[];
  emptyPromoInstructionsTemplates: string[];
  noteTemplate: string;
  relatedContentTitle: string;
  rewardArticleCardTitleTemplate: string;
  rewardArticleCardSubtext: string;
  guideCardTitle: string;
  guideCardSubtext: string;
  faqTitle: string;
  faqs: { question: string; answer: string }[];
  transparencyTemplate: string;
};

const pages: Record<Locale, PageCopy> = {
  pt: {
    locale: 'pt',
    language: 'pt-BR',
    homeLabel: 'Início',
    couponsLabel: 'Cupons',
    category: 'Beleza, moda e lifestyle',
    titleTemplate: 'Cupom YesStyle e código de recompensa {code}: até {newDiscount}% extra',
    descriptionTemplate: 'Código de recompensa {code} oficial da YesStyle: use no campo Reward Code para até {newDiscount}% extra, combinável com cupons promocionais elegíveis no checkout.',
    introTemplate: '{code} é o código de recompensa oficial da YesStyle e soma com os cupons promocionais elegíveis da própria loja.',
    copyAriaPromoTemplate: 'Copiar cupom promocional {promoCode}',
    visit: 'Ir para a YesStyle',
    rewardCodeLabel: 'Código de recompensa',
    rewardFieldNote: 'Cole no campo Reward Code do checkout.',
    firstOrderLabel: '1ª compra',
    nextOrdersLabel: 'Compras seguintes',
    promosSectionTitle: 'Cupons promocionais da YesStyle',
    promosIntroTemplate: 'São cupons da própria YesStyle: vencem, vão no campo Coupon Code e podem somar com o {code}.',
    emptyPromosNoticeTemplate: 'Nenhum cupom promocional verificado no momento.',
    emptyPromosSubtextTemplate: 'O código de recompensa {code} continua ativo no campo Reward Code.',
    proofLabel: 'Ver comprovante oficial',
    validityUnconfirmed: 'Prazo não informado',
    regionUnconfirmed: 'Região não informada',
    freeShippingLabel: 'Frete grátis',
    promoLabels: { validity: 'Validade', region: 'Região' },
    tierTemplate: '{percent} em compras a partir de {amount}',
    noMinimumLabel: 'Sem valor mínimo',
    membersOnlyLabel: 'Só para membros, com login na YesStyle',
    allRegionsLabel: 'Todos os países',
    policyTitle: 'Como funcionam os cupons da YesStyle',
    policyRules: {
      eligible: 'Produtos que participam da promoção. Quando um item fica de fora, a YesStyle avisa na página dele ou no checkout.',
      combinable: 'Sim, com preços em promoção, com o {code} no campo Reward Code e com os YS Points. Com outro cupom, não: é um por pedido.',
      validity: 'Cada cupom tem o seu prazo, no horário GMT, 3 horas à frente de Brasília.',
      shipping: 'O desconto vale só para o preço dos produtos. Frete, reenvio e outras taxas ficam de fora.',
    },
    instructionsTitleTemplate: 'Como aplicar cupons e o código {code} no checkout',
    instructionsTemplates: [
      'Copie o cupom promocional ativo (ex: {promoCode}).',
      'Copie o código de recompensa {code}.',
      'Acesse a YesStyle pelo link oficial da Cecília.',
      'No carrinho/checkout, cole o cupom promocional no campo Coupon Code.',
      'Cole {code} no campo separado Reward Code / Código de Recompensa.',
      'Confirme no resumo do pedido se os dois descontos foram aplicados antes de pagar.',
    ],
    emptyPromoInstructionsTemplates: [
      'Copie o código de recompensa {code}.',
      'Acesse a YesStyle pelo link oficial da Cecília e adicione seus produtos.',
      'No carrinho/checkout, digite {code} no campo Reward Code / Código de Recompensa.',
      'Se houver algum cupom sazonal da loja, tente aplicá-lo no campo Coupon Code.',
      'Confirme o valor final e o desconto aplicado no resumo antes de pagar.',
    ],
    noteTemplate: 'Importante: digite {code} em Reward Code, e cupons de promoção em Coupon Code.',
    relatedContentTitle: 'Guias e artigos da YesStyle',
    rewardArticleCardTitleTemplate: 'Guia do código {code}',
    rewardArticleCardSubtext: 'Passo a passo com telas e dicas',
    guideCardTitle: 'Como encontrar cupons válidos',
    guideCardSubtext: 'Regras de combinação e frete',
    faqTitle: 'Perguntas frequentes sobre cupons YesStyle',
    faqs: [
      { question: 'O código {code} pode ser usado junto com cupons de desconto?', answer: 'O código {code} no campo Reward Code pode ser combinado com cupons promocionais elegíveis no campo Coupon Code. A aceitação dos dois descontos deve ser sempre confirmada no resumo do checkout.' },
      { question: 'Qual a diferença entre Coupon Code e Reward Code?', answer: 'Coupon Code aceita cupons promocionais temporários da loja. Reward Code aceita o código de influenciadora {code} para desconto extra.' },
    ],
    transparencyTemplate: 'Esta página contém links de afiliada. Ao comprar pelo link ou utilizar o código {code}, podemos receber uma comissão sem custo adicional para você.',
  },
  en: {
    locale: 'en',
    language: 'en-US',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: 'Coupons',
    category: 'Beauty, fashion and lifestyle',
    titleTemplate: 'YesStyle Reward Code {code}: Up to {newDiscount}% Extra',
    descriptionTemplate: 'Official YesStyle reward code {code}. Add up to {newDiscount}% extra at checkout on top of eligible promo coupons.',
    introTemplate: '{code} is YesStyle’s official Reward Code, and it stacks with the store’s own eligible promo coupons.',
    copyAriaPromoTemplate: 'Copy promo coupon {promoCode}',
    visit: 'Visit YesStyle',
    rewardCodeLabel: 'Reward Code',
    rewardFieldNote: 'Paste it in the Reward Code field at checkout.',
    firstOrderLabel: 'First order',
    nextOrdersLabel: 'Returning orders',
    promosSectionTitle: 'YesStyle promo coupons',
    promosIntroTemplate: 'These come from YesStyle itself: they expire, go in the Coupon Code field and can stack with {code}.',
    emptyPromosNoticeTemplate: 'No verified promotional coupons active right now.',
    emptyPromosSubtextTemplate: 'The reward code {code} remains active in the Reward Code field.',
    proofLabel: 'View official proof',
    validityUnconfirmed: 'Validity unstated',
    regionUnconfirmed: 'Region unstated',
    freeShippingLabel: 'Free shipping',
    promoLabels: { validity: 'Validity', region: 'Region' },
    tierTemplate: '{percent} off orders of {amount} or more',
    noMinimumLabel: 'No minimum spend',
    membersOnlyLabel: 'Members only: sign in to YesStyle',
    allRegionsLabel: 'All countries',
    policyTitle: 'How YesStyle coupons work',
    policyRules: {
      eligible: 'Products in the promotion. When an item is excluded, YesStyle says so on its page or at checkout.',
      combinable: 'Yes, with sale prices, with {code} in the Reward Code field and with YS Points. Not with another coupon: one per order.',
      validity: 'Each coupon has its own deadline, in GMT.',
      shipping: 'The discount applies to product prices only. Shipping, reshipping and other fees are excluded.',
    },
    instructionsTitleTemplate: 'How to combine coupons and code {code}',
    instructionsTemplates: [
      'Copy any active promo coupon (e.g. {promoCode}).',
      'Copy the reward code {code}.',
      'Open YesStyle via our official link.',
      'At checkout, enter your promo coupon in the Coupon Code field.',
      'Enter {code} in the separate Reward Code field.',
      'Verify that both discounts appear before placing your order.',
    ],
    emptyPromoInstructionsTemplates: [
      'Copy the reward code {code}.',
      'Open YesStyle via our official link and add your items.',
      'At checkout, enter {code} in the Reward Code field.',
      'If any store promo coupon is available, try applying it in Coupon Code.',
      'Confirm the final order summary before placing your order.',
    ],
    noteTemplate: 'Important: enter {code} in Reward Code, not Coupon Code.',
    relatedContentTitle: 'YesStyle guides and reviews',
    rewardArticleCardTitleTemplate: 'Guide to the code {code}',
    rewardArticleCardSubtext: 'Step-by-step with screenshots and tips',
    guideCardTitle: 'How to find valid coupons',
    guideCardSubtext: 'Stacking rules and shipping info',
    faqTitle: 'Frequently asked questions',
    faqs: [
      { question: 'Can I use {code} with a promo coupon?', answer: 'The code {code} in the Reward Code field may be stacked with eligible promo coupons in the Coupon Code field. Stacking eligibility must always be confirmed in the checkout summary.' },
      { question: 'What discount does {code} offer?', answer: 'It adds up to {newDiscount}% extra ({newDiscount}% first order / {returningDiscount}% returning orders).' },
    ],
    transparencyTemplate: 'This page contains affiliate links. If you visit YesStyle through our links or use the code {code}, we may earn a commission at no extra cost to you.',
  },
  es: {
    locale: 'es',
    language: 'es-ES',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: 'Cupones',
    category: 'Belleza, moda y estilo de vida',
    titleTemplate: 'Código de recompensa YesStyle {code}: Hasta {newDiscount}% extra',
    descriptionTemplate: 'Código de recompensa oficial {code} en YesStyle. Suma hasta un {newDiscount}% extra junto con cupones promocionales elegibles al pagar.',
    introTemplate: '{code} es el código de recompensa oficial de YesStyle y se suma a los cupones promocionales elegibles de la propia tienda.',
    copyAriaPromoTemplate: 'Copiar cupón promocional {promoCode}',
    visit: 'Ir a YesStyle',
    rewardCodeLabel: 'Código de recompensa',
    rewardFieldNote: 'Pégalo en el campo Reward Code al pagar.',
    firstOrderLabel: 'Primera compra',
    nextOrdersLabel: 'Compras siguientes',
    promosSectionTitle: 'Cupones promocionales de YesStyle',
    promosIntroTemplate: 'Son cupones de la propia YesStyle: caducan, van en el campo Coupon Code y pueden sumarse a {code}.',
    emptyPromosNoticeTemplate: 'No hay cupones promocionales verificados en este momento.',
    emptyPromosSubtextTemplate: 'El código de recompensa {code} sigue activo en el campo Reward Code.',
    proofLabel: 'Ver comprobante oficial',
    validityUnconfirmed: 'Plazo no informado',
    regionUnconfirmed: 'Región no informada',
    freeShippingLabel: 'Envío gratis',
    promoLabels: { validity: 'Validez', region: 'Región' },
    tierTemplate: '{percent} en pedidos desde {amount}',
    noMinimumLabel: 'Sin compra mínima',
    membersOnlyLabel: 'Solo para miembros, con sesión iniciada en YesStyle',
    allRegionsLabel: 'Todos los países',
    policyTitle: 'Cómo funcionan los cupones de YesStyle',
    policyRules: {
      eligible: 'Productos de la promoción. Si un artículo queda fuera, YesStyle lo indica en su página o al pagar.',
      combinable: 'Sí, con precios rebajados, con {code} en el campo Reward Code y con los YS Points. Con otro cupón, no: uno por pedido.',
      validity: 'Cada cupón tiene su propio plazo, en horario GMT.',
      shipping: 'El descuento se aplica solo al precio de los productos. Envío, reenvío y otras tarifas quedan fuera.',
    },
    instructionsTitleTemplate: 'Cómo usar {code} y cupones',
    instructionsTemplates: [
      'Copia el cupón promocional activo (ej: {promoCode}).',
      'Copia el código de recompensa {code}.',
      'Entra a YesStyle mediante nuestro enlace oficial.',
      'En el checkout, usa el cupón promocional en Coupon Code.',
      'Ingresa {code} en el campo separado Reward Code.',
      'Comprueba ambos descuentos antes de pagar.',
    ],
    emptyPromoInstructionsTemplates: [
      'Copia el código de recompensa {code}.',
      'Entra a YesStyle mediante nuestro enlace oficial y añade tus productos.',
      'En el checkout, ingresa {code} en el campo Reward Code.',
      'Si hay algún cupón promocional activo de la tienda, prueba aplicarlo en Coupon Code.',
      'Comprueba el importe final y el descuento aplicado antes de pagar.',
    ],
    noteTemplate: 'Importante: {code} va en Reward Code, no en Coupon Code.',
    relatedContentTitle: 'Guías YesStyle',
    rewardArticleCardTitleTemplate: 'Guía del código {code}',
    rewardArticleCardSubtext: 'Paso a paso con pantallas y consejos',
    guideCardTitle: 'Cómo encontrar cupones válidos',
    guideCardSubtext: 'Reglas de combinación y envío',
    faqTitle: 'Preguntas frecuentes',
    faqs: [
      { question: '¿Puedo usar {code} con un cupón?', answer: 'El código {code} en el campo Reward Code se puede combinar con cupones promocionales elegibles en Coupon Code, debiendo confirmarse en el resumen del checkout.' },
    ],
    transparencyTemplate: 'Esta página contiene enlaces de afiliado. Si compras mediante el código {code}, podemos recibir una comisión sin coste adicional.',
  },
  fr: {
    locale: 'fr',
    language: 'fr-FR',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: 'Coupons',
    category: 'Beauté, mode et lifestyle',
    titleTemplate: `Code récompense YesStyle {code}${NBSP}: Jusqu’à {newDiscount}${NBSP}% en plus`,
    descriptionTemplate: `Code récompense officiel {code} sur YesStyle. Ajoutez jusqu’à {newDiscount}${NBSP}% de réduction sous réserve d’éligibilité des coupons promo.`,
    introTemplate: '{code} est le code récompense officiel de YesStyle et se cumule avec les coupons promo éligibles de la boutique.',
    copyAriaPromoTemplate: 'Copier le coupon promo {promoCode}',
    visit: 'Aller sur YesStyle',
    rewardCodeLabel: 'Code récompense',
    rewardFieldNote: 'Collez-le dans le champ Reward Code au paiement.',
    firstOrderLabel: 'Première commande',
    nextOrdersLabel: 'Commandes suivantes',
    promosSectionTitle: 'Coupons promo YesStyle',
    promosIntroTemplate: `Ces coupons viennent de YesStyle${NBSP}: ils expirent, se saisissent dans le champ Coupon Code et peuvent se cumuler avec {code}.`,
    emptyPromosNoticeTemplate: 'Aucun coupon promotionnel vérifié pour le moment.',
    emptyPromosSubtextTemplate: 'Le code récompense {code} reste actif dans le champ Reward Code.',
    proofLabel: 'Voir la preuve officielle',
    validityUnconfirmed: 'Délai non précisé',
    regionUnconfirmed: 'Région non précisée',
    freeShippingLabel: 'Livraison gratuite',
    promoLabels: { validity: 'Validité', region: 'Région' },
    tierTemplate: '{percent} dès {amount} d’achat',
    noMinimumLabel: 'Sans minimum d’achat',
    membersOnlyLabel: 'Réservé aux membres connectés à YesStyle',
    allRegionsLabel: 'Tous les pays',
    policyTitle: 'Comment fonctionnent les coupons YesStyle',
    policyRules: {
      eligible: 'Les produits de la promotion. Si un article est exclu, YesStyle l’indique sur sa page ou au paiement.',
      combinable: `Oui, avec les prix soldés, avec {code} dans le champ Reward Code et avec les YS Points. Pas avec un autre coupon${NBSP}: un seul par commande.`,
      validity: 'Chaque coupon a sa propre date limite, à l’heure GMT.',
      shipping: 'La réduction porte uniquement sur le prix des produits. Livraison, réexpédition et autres frais sont exclus.',
    },
    instructionsTitleTemplate: 'Comment utiliser {code} et les coupons',
    instructionsTemplates: [
      'Copiez le coupon promo actif (ex: {promoCode}).',
      'Copiez le code récompense {code}.',
      'Ouvrez YesStyle via notre lien officiel.',
      'Au paiement, saisissez le coupon promo dans Coupon Code.',
      'Saisissez {code} dans le champ séparé Reward Code.',
      'Vérifiez les deux réductions avant de payer.',
    ],
    emptyPromoInstructionsTemplates: [
      'Copiez le code récompense {code}.',
      'Ouvrez YesStyle via notre lien officiel et ajoutez vos produits.',
      'Au paiement, saisissez {code} dans le champ Reward Code.',
      'Si un coupon promo de la boutique est disponible, essayez de l’appliquer dans Coupon Code.',
      'Vérifiez le montant final avant de payer.',
    ],
    noteTemplate: `Important${NBSP}: {code} va dans Reward Code, pas dans Coupon Code.`,
    relatedContentTitle: 'Guides YesStyle',
    rewardArticleCardTitleTemplate: 'Guide du code {code}',
    rewardArticleCardSubtext: 'Pas à pas avec captures et conseils',
    guideCardTitle: 'Comment trouver des coupons valides',
    guideCardSubtext: 'Règles de cumul et livraison',
    faqTitle: 'Questions fréquentes',
    faqs: [
      { question: `Puis-je utiliser {code} avec un coupon${NBSP}?`, answer: 'Le code {code} dans le champ Reward Code peut être cumulé avec les coupons promo éligibles dans Coupon Code, sous réserve de confirmation au moment du paiement.' },
    ],
    transparencyTemplate: 'Cette page contient des liens affiliés. Si vous achetez via {code}, nous pouvons recevoir une commission sans frais supplémentaires.',
  },
  de: {
    locale: 'de',
    language: 'de-DE',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: 'Gutscheine',
    category: 'Beauty, Mode und Lifestyle',
    titleTemplate: 'YesStyle Reward Code {code}: Bis zu {newDiscount} % extra',
    descriptionTemplate: 'Offizieller YesStyle Reward Code {code}. Erhalte bis zu {newDiscount} % extra neben berechtigten Aktionsgutscheinen an der Kasse.',
    introTemplate: '{code} ist der offizielle Reward Code von YesStyle und lässt sich mit berechtigten Aktionsgutscheinen des Shops kombinieren.',
    copyAriaPromoTemplate: 'Aktionsgutschein {promoCode} kopieren',
    visit: 'Zu YesStyle',
    rewardCodeLabel: 'Reward Code',
    rewardFieldNote: 'An der Kasse ins Feld Reward Code einfügen.',
    firstOrderLabel: 'Erstbestellung',
    nextOrdersLabel: 'Folgebestellungen',
    promosSectionTitle: 'Aktionsgutscheine von YesStyle',
    promosIntroTemplate: 'Diese Gutscheine kommen von YesStyle selbst: Sie laufen ab, gehören ins Feld Coupon Code und lassen sich mit {code} kombinieren.',
    emptyPromosNoticeTemplate: 'Derzeit keine verifizierten Aktionsgutscheine aktiv.',
    emptyPromosSubtextTemplate: 'Der Reward Code {code} bleibt im Feld Reward Code aktiv.',
    proofLabel: 'Offiziellen Nachweis anzeigen',
    validityUnconfirmed: 'Frist nicht angegeben',
    regionUnconfirmed: 'Region nicht angegeben',
    freeShippingLabel: 'Kostenloser Versand',
    promoLabels: { validity: 'Gültigkeit', region: 'Region' },
    tierTemplate: '{percent} ab {amount} Bestellwert',
    noMinimumLabel: 'Kein Mindestbestellwert',
    membersOnlyLabel: 'Nur für angemeldete YesStyle-Mitglieder',
    allRegionsLabel: 'Alle Länder',
    policyTitle: 'So funktionieren YesStyle-Gutscheine',
    policyRules: {
      eligible: 'Produkte aus der Aktion. Ist ein Artikel ausgeschlossen, zeigt YesStyle das auf der Produktseite oder an der Kasse an.',
      combinable: 'Ja, mit reduzierten Preisen, mit {code} im Feld Reward Code und mit YS Points. Nicht mit einem weiteren Gutschein: einer pro Bestellung.',
      validity: 'Jeder Gutschein hat eine eigene Frist, nach GMT.',
      shipping: 'Der Rabatt gilt nur für den Warenpreis. Versand, erneuter Versand und andere Gebühren sind ausgenommen.',
    },
    instructionsTitleTemplate: 'So verwendest du {code} & Gutscheine',
    instructionsTemplates: [
      'Kopiere den aktiven Aktionsgutschein (z. B. {promoCode}).',
      'Kopiere den Reward Code {code}.',
      'Öffne YesStyle über unseren offiziellen Link.',
      'Gib den Aktionsgutschein im Feld Coupon Code ein.',
      'Gib {code} im separaten Feld Reward Code ein.',
      'Prüfe beide Rabatte vor dem Bezahlen.',
    ],
    emptyPromoInstructionsTemplates: [
      'Kopiere den Reward Code {code}.',
      'Öffne YesStyle über unseren offiziellen Link und lege Produkte in den Warenkorb.',
      'Gib {code} an der Kasse im Feld Reward Code ein.',
      'Falls ein Shop-Gutschein verfügbar ist, versuche ihn im Feld Coupon Code einzugeben.',
      'Prüfe den Endbetrag vor dem Bezahlen.',
    ],
    noteTemplate: 'Wichtig: {code} gehört in Reward Code, nicht in Coupon Code.',
    relatedContentTitle: 'YesStyle Ratgeber',
    rewardArticleCardTitleTemplate: 'Ratgeber zum Code {code}',
    rewardArticleCardSubtext: 'Schritt-für-Schritt mit Screenshots',
    guideCardTitle: 'Gültige Gutscheine finden',
    guideCardSubtext: 'Kombinationsregeln & Versand',
    faqTitle: 'Häufige Fragen',
    faqs: [
      { question: 'Kann ich {code} mit einem Gutschein nutzen?', answer: 'Der Code {code} im Feld Reward Code kann mit berechtigten Aktionsgutscheinen im Feld Coupon Code kombiniert werden. Die Ausweisung beider Rabatte ist an der Kasse zu prüfen.' },
    ],
    transparencyTemplate: 'Diese Seite enthält Affiliate-Links. Wenn du über {code} kaufst, erhalten wir möglicherweise eine Provision ohne Zusatzkosten.',
  },
  it: {
    locale: 'it',
    language: 'it-IT',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: 'Coupon',
    category: 'Bellezza, moda e lifestyle',
    titleTemplate: 'Codice ricompensa YesStyle {code}: fino al {newDiscount}% in più',
    descriptionTemplate: 'Codice ricompensa ufficiale {code} su YesStyle: inseriscilo nel campo Reward Code per uno sconto extra fino al {newDiscount}%, cumulabile con i coupon promozionali idonei.',
    introTemplate: '{code} è il codice ricompensa ufficiale di YesStyle e si somma ai coupon promozionali idonei del negozio.',
    copyAriaPromoTemplate: 'Copia il coupon promozionale {promoCode}',
    visit: 'Vai su YesStyle',
    rewardCodeLabel: 'Codice ricompensa',
    rewardFieldNote: 'Incollalo nel campo Reward Code al checkout.',
    firstOrderLabel: 'Primo ordine',
    nextOrdersLabel: 'Ordini successivi',
    promosSectionTitle: 'Coupon promozionali YesStyle',
    promosIntroTemplate: 'Sono coupon della stessa YesStyle: scadono, vanno nel campo Coupon Code e possono sommarsi a {code}.',
    emptyPromosNoticeTemplate: 'Al momento non ci sono coupon promozionali verificati.',
    emptyPromosSubtextTemplate: 'Il codice ricompensa {code} resta attivo nel campo Reward Code.',
    proofLabel: 'Vedi la prova ufficiale',
    validityUnconfirmed: 'Scadenza non indicata',
    regionUnconfirmed: 'Regione non indicata',
    freeShippingLabel: 'Spedizione gratuita',
    promoLabels: { validity: 'Validità', region: 'Regione' },
    tierTemplate: '{percent} sugli ordini da {amount}',
    noMinimumLabel: 'Nessuna spesa minima',
    membersOnlyLabel: 'Solo per i membri che hanno effettuato l’accesso a YesStyle',
    allRegionsLabel: 'Tutti i paesi',
    policyTitle: 'Come funzionano i coupon YesStyle',
    policyRules: {
      eligible: 'I prodotti in promozione. Se un articolo è escluso, YesStyle lo indica nella sua pagina o al checkout.',
      combinable: 'Sì, con i prezzi scontati, con {code} nel campo Reward Code e con gli YS Points. Non con un altro coupon: uno per ordine.',
      validity: 'Ogni coupon ha la sua scadenza, in orario GMT.',
      shipping: 'Lo sconto vale solo sul prezzo dei prodotti. Spedizione, rispedizione e altre tariffe sono escluse.',
    },
    instructionsTitleTemplate: 'Come usare {code} e i coupon al checkout',
    instructionsTemplates: [
      'Copia il coupon promozionale attivo (es. {promoCode}).',
      'Copia il codice ricompensa {code}.',
      'Apri YesStyle dal link ufficiale di Cecília.',
      'Al checkout, incolla il coupon promozionale nel campo Coupon Code.',
      'Incolla {code} nel campo separato Reward Code.',
      'Controlla nel riepilogo dell’ordine che entrambi gli sconti siano applicati prima di pagare.',
    ],
    emptyPromoInstructionsTemplates: [
      'Copia il codice ricompensa {code}.',
      'Apri YesStyle dal link ufficiale di Cecília e aggiungi i tuoi prodotti.',
      'Al checkout, inserisci {code} nel campo Reward Code.',
      'Se c’è un coupon stagionale del negozio, prova ad applicarlo nel campo Coupon Code.',
      'Controlla l’importo finale e lo sconto applicato prima di pagare.',
    ],
    noteTemplate: 'Importante: {code} va nel campo Reward Code, i coupon promozionali in Coupon Code.',
    relatedContentTitle: 'Guide YesStyle',
    rewardArticleCardTitleTemplate: 'Guida al codice {code}',
    rewardArticleCardSubtext: 'Passo passo con schermate e consigli',
    guideCardTitle: 'Come trovare coupon validi',
    guideCardSubtext: 'Regole di cumulo e spedizione',
    faqTitle: 'Domande frequenti',
    faqs: [
      { question: 'Posso usare {code} insieme a un coupon?', answer: 'Il codice {code} nel campo Reward Code si può cumulare con i coupon promozionali idonei nel campo Coupon Code. Controlla sempre nel riepilogo del checkout che entrambi gli sconti siano applicati.' },
    ],
    transparencyTemplate: 'Questa pagina contiene link di affiliazione. Se acquisti tramite il link o usi il codice {code}, potremmo ricevere una commissione senza costi aggiuntivi per te.',
  },
  ko: {
    locale: 'ko',
    language: 'ko-KR',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: '쿠폰',
    category: '뷰티, 패션, 라이프스타일',
    titleTemplate: 'YesStyle 리워드 코드 {code}: 추가 {newDiscount}% 할인',
    descriptionTemplate: '공식 YesStyle 리워드 코드 {code}. 결제 시 대상 프로모션 쿠폰과 함께 최대 추가 {newDiscount}% 혜택을 받으세요.',
    introTemplate: '{code}은 공식 YesStyle 리워드 코드로, 스토어의 대상 프로모션 쿠폰과 함께 쓸 수 있습니다.',
    copyAriaPromoTemplate: '프로모션 쿠폰 {promoCode} 복사',
    visit: 'YesStyle 방문',
    rewardCodeLabel: '리워드 코드',
    rewardFieldNote: '결제할 때 Reward Code 칸에 붙여 넣으세요.',
    firstOrderLabel: '첫 구매',
    nextOrdersLabel: '재구매',
    promosSectionTitle: 'YesStyle 프로모션 쿠폰',
    promosIntroTemplate: 'YesStyle이 직접 제공하는 쿠폰입니다. 기한이 있고, Coupon Code 칸에 입력하며, {code}과 함께 쓸 수 있습니다.',
    emptyPromosNoticeTemplate: '현재 검증된 프로모션 쿠폰이 없습니다.',
    emptyPromosSubtextTemplate: '리워드 코드 {code}은 Reward Code 칸에서 계속 활성화 상태입니다.',
    proofLabel: '공식 증빙 보기',
    validityUnconfirmed: '기한 미기재',
    regionUnconfirmed: '지역 미기재',
    freeShippingLabel: '무료 배송',
    promoLabels: { validity: '유효기간', region: '적용지역' },
    tierTemplate: '{amount} 이상 구매 시 {percent} 할인',
    noMinimumLabel: '최소 구매 금액 없음',
    membersOnlyLabel: 'YesStyle 회원 전용(로그인 필요)',
    allRegionsLabel: '전 세계',
    policyTitle: 'YesStyle 쿠폰 이용 규칙',
    policyRules: {
      eligible: '프로모션 대상 상품입니다. 제외되는 상품은 YesStyle이 상품 페이지나 결제 단계에서 알려 줍니다.',
      combinable: '네. 할인가, Reward Code 칸의 {code}, YS Points와 함께 쓸 수 있습니다. 다른 쿠폰과는 함께 쓸 수 없으며 주문당 하나만 적용됩니다.',
      validity: '쿠폰마다 기한이 다르며 GMT 기준입니다.',
      shipping: '할인은 상품 가격에만 적용되며 배송비, 재발송 비용, 기타 수수료는 제외됩니다.',
    },
    instructionsTitleTemplate: '{code} 및 쿠폰 사용 방법',
    instructionsTemplates: [
      '활성 프로모션 쿠폰(예: {promoCode})을 복사하세요.',
      '리워드 코드 {code}을 복사하세요.',
      '공식 링크를 통해 YesStyle에 접속하세요.',
      '결제 시 Coupon Code 칸에 프로모션 쿠폰을 입력하세요.',
      '별도의 Reward Code 칸에 {code}을 입력하세요.',
      '결제 전 두 할인 모두 적용되었는지 확인하세요.',
    ],
    emptyPromoInstructionsTemplates: [
      '리워드 코드 {code}을 복사하세요.',
      '공식 링크를 통해 YesStyle에 접속하고 상품을 담으세요.',
      '결제 시 Reward Code 칸에 {code}을 입력하세요.',
      '쇼핑몰 프로모션 쿠폰이 있다면 Coupon Code 칸에 적용해 보세요.',
      '결제 전 최종 할인 금액을 확인하세요.',
    ],
    noteTemplate: '중요: {code}은 Coupon Code가 아닌 Reward Code에 입력하세요.',
    relatedContentTitle: 'YesStyle 가이드',
    rewardArticleCardTitleTemplate: '{code} 코드 사용 가이드',
    rewardArticleCardSubtext: '스크린샷과 함께하는 단계별 가이드',
    guideCardTitle: '유효한 쿠폰 찾는 방법',
    guideCardSubtext: '중복 적용 규칙 및 배송',
    faqTitle: '자주 묻는 질문',
    faqs: [
      { question: '{code} 코드를 다른 쿠폰과 함께 사용할 수 있나요?', answer: 'Reward Code 칸의 {code} 코드는 Coupon Code 칸의 대상 프로모션 쿠폰과 함께 적용될 수 있으며, 최종 적용 여부는 결제 요약 화면에서 확인해야 합니다.' },
    ],
    transparencyTemplate: '이 페이지에는 제휴 링크가 포함되어 있습니다. 코드를 사용하여 구매 시 수수료를 지급받을 수 있습니다.',
  },
  ja: {
    locale: 'ja',
    language: 'ja-JP',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: 'クーポン',
    category: 'ビューティー・ファッション・ライフスタイル',
    titleTemplate: 'YesStyle リワードコード {code}：さらに{newDiscount}%オフ',
    descriptionTemplate: 'YesStyle公式リワードコード{code}。チェックアウト時に対象のプロモーションクーポンと併用して最大{newDiscount}%追加オフ。',
    introTemplate: '{code}はYesStyle公式のリワードコードで、ストアの対象プロモーションクーポンと併用できます。',
    copyAriaPromoTemplate: 'クーポンコード {promoCode} をコピー',
    visit: 'YesStyleへ',
    rewardCodeLabel: 'リワードコード',
    rewardFieldNote: 'チェックアウトで Reward Code 欄に貼り付けます。',
    firstOrderLabel: '初回',
    nextOrdersLabel: '2回目以降',
    promosSectionTitle: 'YesStyleのクーポン',
    promosIntroTemplate: 'YesStyle独自のクーポンです。期限があり、Coupon Code 欄に入力し、{code}と併用できます。',
    emptyPromosNoticeTemplate: '現在、検証済みのプロモーションクーポンはありません。',
    emptyPromosSubtextTemplate: 'リワードコード {code} は Reward Code 欄で引き続き有効です。',
    proofLabel: '公式証明を見る',
    validityUnconfirmed: '期限未記載',
    regionUnconfirmed: '地域未記載',
    freeShippingLabel: '送料無料',
    promoLabels: { validity: '有効期限', region: '対象地域' },
    tierTemplate: '{amount}以上の購入で{percent}オフ',
    noMinimumLabel: '最低購入金額なし',
    membersOnlyLabel: 'YesStyle会員限定（ログインが必要）',
    allRegionsLabel: '全世界',
    policyTitle: 'YesStyleクーポンのルール',
    policyRules: {
      eligible: 'キャンペーン対象の商品です。対象外の商品は、商品ページかチェックアウトでYesStyleが表示します。',
      combinable: 'はい。セール価格、Reward Code 欄の{code}、YS Pointsと併用できます。ほかのクーポンとは併用できず、1回の注文に1枚までです。',
      validity: 'クーポンごとに期限があり、時刻はGMT基準です。',
      shipping: '割引は商品価格のみが対象です。送料、再発送料、その他の手数料は対象外です。',
    },
    instructionsTitleTemplate: '{code} とクーポンの使い方',
    instructionsTemplates: [
      '有効なプロモーションクーポン（例：{promoCode}）をコピーします。',
      'リワードコード {code} をコピーします。',
      '公式リンクから YesStyle にアクセスします。',
      'チェックアウト時に Coupon Code 欄へプロモクーポンを入力します。',
      '別欄の Reward Code 欄へ {code} を入力します。',
      '注文前に両方の割引を確認します。',
    ],
    emptyPromoInstructionsTemplates: [
      'リワードコード {code} をコピーします。',
      '公式リンクから YesStyle にアクセスし、商品をカートに入れます。',
      'チェックアウト時に Reward Code 欄へ {code} を入力します。',
      'ショップクーポンがある場合は Coupon Code 欄への入力をお試しください。',
      '注文確定前に最終金額を確認します。',
    ],
    noteTemplate: '重要：{code}はCoupon CodeではなくReward Codeに入力してください。',
    relatedContentTitle: 'YesStyle ガイド',
    rewardArticleCardTitleTemplate: '{code} コードの使い方ガイド',
    rewardArticleCardSubtext: 'スクリーンショット付きのステップ解説',
    guideCardTitle: '有効なクーポンの探し方',
    guideCardSubtext: '併用ルールと送料について',
    faqTitle: 'よくある質問',
    faqs: [
      { question: '{code}はほかのクーポンと併用できますか？', answer: 'Reward Code 欄の {code} は対象のプロモーションクーポンと併用できる場合があります。両方の割引が適用されるかは注文確定前のチェックアウト画面で確認してください。' },
    ],
    transparencyTemplate: 'このページにはアフィリエイトリンクが含まれる場合があります。{code}を利用して購入すると報酬を得ることがあります。',
  },
  'zh-hant': {
    locale: 'zh-hant',
    language: 'zh-HK',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: '優惠碼',
    category: '美妝、時尚與生活風格',
    titleTemplate: 'YesStyle 獎勵碼 {code}：額外 {newDiscount}% 優惠',
    descriptionTemplate: 'YesStyle 官方獎勵碼 {code}。在結帳時可與適用促銷優惠碼組合使用，額外享有最高 {newDiscount}% 優惠。',
    introTemplate: '{code} 是 YesStyle 官方獎勵碼，可與商店的適用促銷優惠碼疊加使用。',
    copyAriaPromoTemplate: '複製促銷優惠碼 {promoCode}',
    visit: '前往 YesStyle',
    rewardCodeLabel: '獎勵碼',
    rewardFieldNote: '結帳時貼到 Reward Code 欄位。',
    firstOrderLabel: '首購',
    nextOrdersLabel: '複購',
    promosSectionTitle: 'YesStyle 促銷優惠碼',
    promosIntroTemplate: '這些是 YesStyle 自家的優惠碼：有使用期限，填在 Coupon Code 欄位，可與 {code} 疊加。',
    emptyPromosNoticeTemplate: '目前沒有已驗證的促銷優惠碼。',
    emptyPromosSubtextTemplate: '獎勵碼 {code} 在 Reward Code 欄位仍保持有效。',
    proofLabel: '查看官方證明',
    validityUnconfirmed: '未註明期限',
    regionUnconfirmed: '未註明地區',
    freeShippingLabel: '免運費',
    promoLabels: { validity: '有效期限', region: '適用地區' },
    tierTemplate: '滿 {amount} 享 {percent} 折扣',
    noMinimumLabel: '沒有最低消費',
    membersOnlyLabel: '只限已登入的 YesStyle 會員',
    allRegionsLabel: '全球',
    policyTitle: 'YesStyle 優惠碼規則',
    policyRules: {
      eligible: '參加活動的商品。如有商品不適用，YesStyle 會在商品頁面或結帳時註明。',
      combinable: '可以，特價、Reward Code 欄位的 {code} 及 YS Points 都可同時使用。但不可與其他優惠碼同時使用，每張訂單只限一個。',
      validity: '每個優惠碼都有各自的期限，以 GMT 時間計算。',
      shipping: '折扣只適用於商品價格，運費、重新寄送費用及其他收費除外。',
    },
    instructionsTitleTemplate: '如何組合使用 {code} 與優惠碼',
    instructionsTemplates: [
      '複製有效的促銷優惠碼（例如 {promoCode}）。',
      '複製獎勵碼 {code}。',
      '透過官方連結前往 YesStyle。',
      '結帳時在 Coupon Code 欄位輸入促銷優惠碼。',
      '在獨立的 Reward Code 欄位輸入 {code}。',
      '付款前確認兩項優惠皆已套用。',
    ],
    emptyPromoInstructionsTemplates: [
      '複製獎勵碼 {code}。',
      '透過官方連結前往 YesStyle 並選購商品。',
      '結帳時在 Reward Code 欄位輸入 {code}。',
      '如有店家優惠碼，可嘗試於 Coupon Code 欄位輸入。',
      '付款前確認最終折扣與金額。',
    ],
    noteTemplate: '重要：{code} 應輸入 Reward Code，而不是 Coupon Code。',
    relatedContentTitle: 'YesStyle 指南',
    rewardArticleCardTitleTemplate: '{code} 優惠碼使用指南',
    rewardArticleCardSubtext: '附螢幕截圖的圖文教學',
    guideCardTitle: '如何尋找有效優惠碼',
    guideCardSubtext: '疊加規則與免運條件',
    faqTitle: '常見問題',
    faqs: [
      { question: '{code} 可以與其他優惠碼同時使用嗎？', answer: 'Reward Code 欄位的 {code} 可與 Coupon Code 欄位的適用促銷優惠碼組合使用，實際疊加結果須以結帳明細為準。' },
    ],
    transparencyTemplate: '此頁面包含聯盟連結。使用 {code} 購物時，我們可能會獲得佣金。',
  },
  'zh-hans': {
    locale: 'zh-hans',
    language: 'zh-CN',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: '优惠码',
    category: '美妆、时尚与生活方式',
    titleTemplate: 'YesStyle 奖励码 {code}：额外 {newDiscount}% 优惠',
    descriptionTemplate: 'YesStyle 官方奖励码 {code}。在结账时可与适用促销优惠码组合使用，额外享受最高 {newDiscount}% 优惠。',
    introTemplate: '{code} 是 YesStyle 官方奖励码，可与商店的适用促销优惠码叠加使用。',
    copyAriaPromoTemplate: '复制促销优惠码 {promoCode}',
    visit: '前往 YesStyle',
    rewardCodeLabel: '奖励码',
    rewardFieldNote: '结账时粘贴到 Reward Code 栏位。',
    firstOrderLabel: '首购',
    nextOrdersLabel: '复购',
    promosSectionTitle: 'YesStyle 促销优惠码',
    promosIntroTemplate: '这些是 YesStyle 自家的优惠码：有使用期限，填在 Coupon Code 栏位，可与 {code} 叠加。',
    emptyPromosNoticeTemplate: '目前没有已验证的促销优惠码。',
    emptyPromosSubtextTemplate: '奖励码 {code} 在 Reward Code 栏位仍保持有效。',
    proofLabel: '查看官方证明',
    validityUnconfirmed: '未注明期限',
    regionUnconfirmed: '未注明地区',
    freeShippingLabel: '免运费',
    promoLabels: { validity: '有效期限', region: '适用地区' },
    tierTemplate: '满 {amount} 享 {percent} 折扣',
    noMinimumLabel: '无最低消费',
    membersOnlyLabel: '仅限已登录的 YesStyle 会员',
    allRegionsLabel: '全球',
    policyTitle: 'YesStyle 优惠码规则',
    policyRules: {
      eligible: '参加活动的商品。如有商品不适用，YesStyle 会在商品页面或结账时注明。',
      combinable: '可以，特价、Reward Code 栏位的 {code} 和 YS Points 都能叠加使用。但不能与其他优惠码叠加，每笔订单只限一个。',
      validity: '每个优惠码都有各自的期限，按 GMT 时间计算。',
      shipping: '折扣仅适用于商品价格，运费、重新寄送费用和其他费用除外。',
    },
    instructionsTitleTemplate: '如何组合使用 {code} 与优惠码',
    instructionsTemplates: [
      '复制有效的促销优惠码（例如 {promoCode}）。',
      '复制奖励码 {code}。',
      '通过官方链接前往 YesStyle。',
      '结账时在 Coupon Code 栏位输入促销优惠码。',
      '在独立的 Reward Code 栏位输入 {code}。',
      '付款前确认两项优惠均已应用。',
    ],
    emptyPromoInstructionsTemplates: [
      '复制奖励码 {code}。',
      '通过官方链接前往 YesStyle 并选购商品。',
      '结账时在 Reward Code 栏位输入 {code}。',
      '如有店家优惠码，可尝试于 Coupon Code 栏位输入。',
      '付款前确认最终折扣与金额。',
    ],
    noteTemplate: '重要：{code} 应输入 Reward Code，而不是 Coupon Code。',
    relatedContentTitle: 'YesStyle 指南',
    rewardArticleCardTitleTemplate: '{code} 优惠码使用指南',
    rewardArticleCardSubtext: '附屏幕截图的图文教学',
    guideCardTitle: '如何寻找有效优惠码',
    guideCardSubtext: '叠加规则与免运条件',
    faqTitle: '常见问题',
    faqs: [
      { question: '{code} 可以和其他优惠码一起使用吗？', answer: 'Reward Code 栏位的 {code} 可与 Coupon Code 栏位的适用促销优惠码组合使用，实际叠加结果须以结账明细为準。' },
    ],
    transparencyTemplate: '此页面包含联盟链接。使用 {code} 购物时，我们可能会获得佣金。',
  },
};

export const yesStyleLocales = Object.keys(pages) as Locale[];

export function getYesStylePage(locale: string): PageCopy | null {
  return pages[locale as Locale] || null;
}
