import type { Locale } from '@/lib/i18n/locales';

// Textos da página de cupons da YesStyle nos 10 idiomas. {code}, {newDiscount}, {returningDiscount}
// e {promoCode} são preenchidos com os dados de data/coupons/yesstyle.json.
export type PageCopy = {
  locale: Locale;
  language: string;
  homeLabel: string;
  couponsLabel: string;
  eyebrow: string;
  titleTemplate: string;
  descriptionTemplate: string;
  introTemplate: string;
  updated: string;
  copy: string;
  copied: string;
  copyAriaTemplate: string;
  copyAriaPromoTemplate: string;
  visit: string;
  rewardCardBadge: string;
  rewardCardDescriptionTemplate: string;
  rewardDiscountValueTemplate: string;
  promosSectionTitle: string;
  emptyPromosNoticeTemplate: string;
  emptyPromosSubtextTemplate: string;
  proofLabel: string;
  validityUnconfirmed: string;
  regionUnconfirmed: string;
  freeShippingLabel: string;
  tableHeaders: {
    type: string;
    code: string;
    discount: string;
    validity: string;
    region: string;
    verified: string;
  };
  offerTypeReward: string;
  offerTypeCoupon: string;
  details: string;
  codeLabel: string;
  discountLabel: string;
  discountValueTemplate: string;
  fieldLabel: string;
  fieldValue: string;
  instructionsTitleTemplate: string;
  instructionsTemplates: string[];
  emptyPromoInstructionsTemplates: string[];
  noteTemplate: string;
  relatedContentTitle: string;
  rewardArticleCardTitleTemplate: string;
  rewardArticleCardSubtext: string;
  guideCardTitle: string;
  guideCardSubtext: string;
  faqTitle: string;
  faqs: { question: string; answer: string }[];
  transparencyTemplate: string;
};

const pages: Record<Locale, PageCopy> = {
  pt: {
    locale: 'pt',
    language: 'pt-BR',
    homeLabel: 'Início',
    couponsLabel: 'Cupons',
    eyebrow: 'Cupons e Código de Recompensa YesStyle',
    titleTemplate: 'Cupom YesStyle {code}: Até {newDiscount}% OFF Extra Elegível',
    descriptionTemplate: 'Código de recompensa {code} oficial da YesStyle: use no campo Reward Code para até {newDiscount}% extra, combinável com cupons promocionais elegíveis no checkout.',
    introTemplate: '{code} é o código de recompensa oficial da YesStyle. Digite no campo Reward Code para somar até {newDiscount}% extra ({newDiscount}% na 1ª compra / {returningDiscount}% em compras recorrentes) aos cupons promocionais ativos elegíveis.',
    updated: 'Atualizado em',
    copy: 'Copiar código',
    copied: 'Copiado!',
    copyAriaTemplate: 'Copiar código {code}',
    copyAriaPromoTemplate: 'Copiar cupom promocional {promoCode}',
    visit: 'Ir para a YesStyle',
    rewardCardBadge: 'Reward Code (Ativo)',
    rewardCardDescriptionTemplate: 'Código de influenciadora ativo no programa. Digite no campo Reward Code para somar até {newDiscount}% extras aos cupons promocionais elegíveis.',
    rewardDiscountValueTemplate: 'Até {newDiscount}% OFF extra ({newDiscount}% 1ª compra / {returningDiscount}% recorrente)',
    promosSectionTitle: 'Cupons Promocionais Verificados',
    emptyPromosNoticeTemplate: 'Nenhum cupom promocional verificado no momento.',
    emptyPromosSubtextTemplate: 'O código de recompensa {code} continua ativo no campo Reward Code.',
    proofLabel: 'Ver comprovante oficial',
    validityUnconfirmed: 'Prazo não informado',
    regionUnconfirmed: 'Região não informada',
    freeShippingLabel: 'Frete Grátis',
    tableHeaders: {
      type: 'Tipo',
      code: 'Código',
      discount: 'Desconto',
      validity: 'Validade',
      region: 'Região',
      verified: 'Verificado',
    },
    offerTypeReward: 'Código de Recompensa',
    offerTypeCoupon: 'Cupom Promocional',
    details: 'Detalhes da oferta',
    codeLabel: 'Código',
    discountLabel: 'Desconto',
    discountValueTemplate: 'Até {newDiscount}% extra ({newDiscount}% novos clientes / {returningDiscount}% clientes recorrentes)',
    fieldLabel: 'Campo no Checkout',
    fieldValue: 'Reward Code / Código de Recompensa',
    instructionsTitleTemplate: 'Como aplicar cupons e o código {code} no checkout',
    instructionsTemplates: [
      'Copie o cupom promocional ativo (ex: {promoCode}).',
      'Copie o código de recompensa {code}.',
      'Acesse a YesStyle pelo link oficial da Cecília.',
      'No carrinho/checkout, cole o cupom promocional no campo Coupon Code.',
      'Cole {code} no campo separado Reward Code / Código de Recompensa.',
      'Confirme no resumo do pedido se os dois descontos foram aplicados antes de pagar.',
    ],
    emptyPromoInstructionsTemplates: [
      'Copie o código de recompensa {code}.',
      'Acesse a YesStyle pelo link oficial da Cecília e adicione seus produtos.',
      'No carrinho/checkout, digite {code} no campo Reward Code / Código de Recompensa.',
      'Se houver algum cupom sazonal da loja, tente aplicá-lo no campo Coupon Code.',
      'Confirme o valor final e o desconto aplicado no resumo antes de pagar.',
    ],
    noteTemplate: 'Importante: digite {code} em Reward Code, e cupons de promoção em Coupon Code.',
    relatedContentTitle: 'Guia e Artigos YesStyle',
    rewardArticleCardTitleTemplate: 'Guia do Código {code}',
    rewardArticleCardSubtext: 'Passo a passo com telas e dicas',
    guideCardTitle: 'Como Encontrar Cupons Válidos',
    guideCardSubtext: 'Regras de combinação e frete',
    faqTitle: 'Perguntas Frequentes sobre Cupons YesStyle',
    faqs: [
      { question: 'O código {code} pode ser usado junto com cupons de desconto?', answer: 'O código {code} no campo Reward Code pode ser combinado com cupons promocionais elegíveis no campo Coupon Code. A aceitação dos dois descontos deve ser sempre confirmada no resumo do checkout.' },
      { question: 'Qual a diferença entre Coupon Code e Reward Code?', answer: 'Coupon Code aceita cupons promocionais temporários da loja. Reward Code aceita o código de influenciadora {code} para desconto extra.' },
    ],
    transparencyTemplate: 'Esta página contém links de afiliada. Ao comprar pelo link ou utilizar o código {code}, podemos receber uma comissão sem custo adicional para você.',
  },
  en: {
    locale: 'en',
    language: 'en-US',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: 'Coupons',
    eyebrow: 'YesStyle Coupons & Reward Code',
    titleTemplate: 'YesStyle Reward Code {code}: Up to {newDiscount}% Extra',
    descriptionTemplate: 'Official YesStyle reward code {code}. Add up to {newDiscount}% extra at checkout on top of eligible promo coupons.',
    introTemplate: '{code} is the official YesStyle Reward Code. Enter it in the Reward Code field to add up to {newDiscount}% extra ({newDiscount}% on 1st order / {returningDiscount}% on returning orders) on top of eligible active promo codes.',
    updated: 'Verified',
    copy: 'Copy code',
    copied: 'Copied!',
    copyAriaTemplate: 'Copy code {code}',
    copyAriaPromoTemplate: 'Copy promo coupon {promoCode}',
    visit: 'Visit YesStyle',
    rewardCardBadge: 'Reward Code (Active)',
    rewardCardDescriptionTemplate: 'Active influencer reward code. Enter in the Reward Code field to stack up to {newDiscount}% extra with eligible promo coupons.',
    rewardDiscountValueTemplate: 'Up to {newDiscount}% extra ({newDiscount}% 1st order / {returningDiscount}% returning)',
    promosSectionTitle: 'Verified Promotional Coupons',
    emptyPromosNoticeTemplate: 'No verified promotional coupons active right now.',
    emptyPromosSubtextTemplate: 'The reward code {code} remains active in the Reward Code field.',
    proofLabel: 'View official proof',
    validityUnconfirmed: 'Validity unstated',
    regionUnconfirmed: 'Region unstated',
    freeShippingLabel: 'Free Shipping',
    tableHeaders: {
      type: 'Type',
      code: 'Code',
      discount: 'Discount',
      validity: 'Validity',
      region: 'Region',
      verified: 'Verified',
    },
    offerTypeReward: 'Reward Code',
    offerTypeCoupon: 'Promo Coupon',
    details: 'Offer details',
    codeLabel: 'Code',
    discountLabel: 'Discount',
    discountValueTemplate: 'Up to {newDiscount}% extra ({newDiscount}% new customers / {returningDiscount}% returning customers)',
    fieldLabel: 'Checkout Field',
    fieldValue: 'Reward Code',
    instructionsTitleTemplate: 'How to combine coupons and code {code}',
    instructionsTemplates: [
      'Copy any active promo coupon (e.g. {promoCode}).',
      'Copy the reward code {code}.',
      'Open YesStyle via our official link.',
      'At checkout, enter your promo coupon in the Coupon Code field.',
      'Enter {code} in the separate Reward Code field.',
      'Verify that both discounts appear before placing your order.',
    ],
    emptyPromoInstructionsTemplates: [
      'Copy the reward code {code}.',
      'Open YesStyle via our official link and add your items.',
      'At checkout, enter {code} in the Reward Code field.',
      'If any store promo coupon is available, try applying it in Coupon Code.',
      'Confirm the final order summary before placing your order.',
    ],
    noteTemplate: 'Important: enter {code} in Reward Code, not Coupon Code.',
    relatedContentTitle: 'YesStyle Guides & Reviews',
    rewardArticleCardTitleTemplate: 'Guide for Code {code}',
    rewardArticleCardSubtext: 'Step-by-step with screenshots and tips',
    guideCardTitle: 'How to Find Valid Coupons',
    guideCardSubtext: 'Stacking rules and shipping info',
    faqTitle: 'Frequently Asked Questions',
    faqs: [
      { question: 'Can I use {code} with a promo coupon?', answer: 'The code {code} in the Reward Code field may be stacked with eligible promo coupons in the Coupon Code field. Stacking eligibility must always be confirmed in the checkout summary.' },
      { question: 'What discount does {code} offer?', answer: 'It adds up to {newDiscount}% extra ({newDiscount}% first order / {returningDiscount}% returning orders).' },
    ],
    transparencyTemplate: 'This page contains affiliate links. If you visit YesStyle through our links or use the code {code}, we may earn a commission at no extra cost to you.',
  },
  es: {
    locale: 'es',
    language: 'es-ES',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: 'Cupones',
    eyebrow: 'Cupones y Código de Recompensa YesStyle',
    titleTemplate: 'Código de recompensa YesStyle {code}: Hasta {newDiscount}% extra',
    descriptionTemplate: 'Código de recompensa oficial {code} en YesStyle. Suma hasta un {newDiscount}% extra junto con cupones promocionales elegibles al pagar.',
    introTemplate: '{code} es el código de recompensa oficial de YesStyle. Úsalo en el campo Reward Code para sumar hasta un {newDiscount}% extra ({newDiscount}% en 1ª compra / {returningDiscount}% en compras siguientes).',
    updated: 'Verificado',
    copy: 'Copiar código',
    copied: '¡Copiado!',
    copyAriaTemplate: 'Copiar código {code}',
    copyAriaPromoTemplate: 'Copiar cupón promocional {promoCode}',
    visit: 'Ir a YesStyle',
    rewardCardBadge: 'Código de Recompensa (Activo)',
    rewardCardDescriptionTemplate: 'Código de influencer activo. Úsalo en el campo Reward Code para sumar hasta {newDiscount}% extra con cupones elegibles.',
    rewardDiscountValueTemplate: 'Hasta {newDiscount}% extra ({newDiscount}% 1ª compra / {returningDiscount}% habitual)',
    promosSectionTitle: 'Cupones Promocionales Verificados',
    emptyPromosNoticeTemplate: 'No hay cupones promocionales verificados en este momento.',
    emptyPromosSubtextTemplate: 'El código de recompensa {code} sigue activo en el campo Reward Code.',
    proofLabel: 'Ver comprobante oficial',
    validityUnconfirmed: 'Plazo no informado',
    regionUnconfirmed: 'Región no informada',
    freeShippingLabel: 'Envío Gratis',
    tableHeaders: {
      type: 'Tipo',
      code: 'Código',
      discount: 'Descuento',
      validity: 'Validez',
      region: 'Región',
      verified: 'Verificado',
    },
    offerTypeReward: 'Código de Recompensa',
    offerTypeCoupon: 'Cupón Promocional',
    details: 'Detalles del código',
    codeLabel: 'Código',
    discountLabel: 'Descuento',
    discountValueTemplate: 'Hasta {newDiscount}% extra ({newDiscount}% nuevos clientes / {returningDiscount}% clientes habituales)',
    fieldLabel: 'Campo en Checkout',
    fieldValue: 'Reward Code',
    instructionsTitleTemplate: 'Cómo usar {code} y cupones',
    instructionsTemplates: [
      'Copia el cupón promocional activo (ej: {promoCode}).',
      'Copia el código de recompensa {code}.',
      'Entra a YesStyle mediante nuestro enlace oficial.',
      'En el checkout, usa el cupón promocional en Coupon Code.',
      'Ingresa {code} en el campo separado Reward Code.',
      'Comprueba ambos descuentos antes de pagar.',
    ],
    emptyPromoInstructionsTemplates: [
      'Copia el código de recompensa {code}.',
      'Entra a YesStyle mediante nuestro enlace oficial y añade tus productos.',
      'En el checkout, ingresa {code} en el campo Reward Code.',
      'Si hay algún cupón promocional activo de la tienda, prueba aplicarlo en Coupon Code.',
      'Comprueba el importe final y el descuento aplicado antes de pagar.',
    ],
    noteTemplate: 'Importante: {code} va en Reward Code, no en Coupon Code.',
    relatedContentTitle: 'Guías YesStyle',
    rewardArticleCardTitleTemplate: 'Guía del código {code}',
    rewardArticleCardSubtext: 'Paso a paso con pantallas y consejos',
    guideCardTitle: 'Cómo encontrar cupones válidos',
    guideCardSubtext: 'Reglas de combinación y envío',
    faqTitle: 'Preguntas Frecuentes',
    faqs: [
      { question: '¿Puedo usar {code} con un cupón?', answer: 'El código {code} en el campo Reward Code se puede combinar con cupones promocionales elegibles en Coupon Code, debiendo confirmarse en el resumen del checkout.' },
    ],
    transparencyTemplate: 'Esta página contiene enlaces de afiliado. Si compras mediante el código {code}, podemos recibir una comisión sin coste adicional.',
  },
  fr: {
    locale: 'fr',
    language: 'fr-FR',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: 'Coupons',
    eyebrow: 'Coupons et Code Récompense YesStyle',
    titleTemplate: 'Code récompense YesStyle {code} : Jusqu’à {newDiscount} % en plus',
    descriptionTemplate: 'Code récompense officiel {code} sur YesStyle. Ajoutez jusqu’à {newDiscount} % de réduction sous réserve d’éligibilité des coupons promo.',
    introTemplate: '{code} est le code récompense officiel de YesStyle. Saisissez-le dans le champ Reward Code pour ajouter jusqu’à {newDiscount} % ({newDiscount} % 1ère commande / {returningDiscount} % commandes suivantes).',
    updated: 'Vérifié',
    copy: 'Copier le code',
    copied: 'Copié !',
    copyAriaTemplate: 'Copier le code {code}',
    copyAriaPromoTemplate: 'Copier le coupon promo {promoCode}',
    visit: 'Aller sur YesStyle',
    rewardCardBadge: 'Code Récompense (Actif)',
    rewardCardDescriptionTemplate: 'Code influenceur actif. Saisissez-le dans le champ Reward Code pour ajouter jusqu’à {newDiscount} % de réduction avec les coupons éligibles.',
    rewardDiscountValueTemplate: 'Jusqu’à {newDiscount} % extra ({newDiscount} % 1ère commande / {returningDiscount} % suivantes)',
    promosSectionTitle: 'Coupons Promotionnels Vérifiés',
    emptyPromosNoticeTemplate: 'Aucun coupon promotionnel vérifié pour le moment.',
    emptyPromosSubtextTemplate: 'Le code récompense {code} reste actif dans le champ Reward Code.',
    proofLabel: 'Voir la preuve officielle',
    validityUnconfirmed: 'Délai non précisé',
    regionUnconfirmed: 'Région non précisée',
    freeShippingLabel: 'Livraison Gratuite',
    tableHeaders: {
      type: 'Type',
      code: 'Code',
      discount: 'Réduction',
      validity: 'Validité',
      region: 'Région',
      verified: 'Vérifié',
    },
    offerTypeReward: 'Code Récompense',
    offerTypeCoupon: 'Coupon Promo',
    details: 'Détails du code',
    codeLabel: 'Code',
    discountLabel: 'Réduction',
    discountValueTemplate: 'Jusqu’à {newDiscount} % extra ({newDiscount} % nouveaux clients / {returningDiscount} % clients réguliers)',
    fieldLabel: 'Champ au Paiement',
    fieldValue: 'Reward Code',
    instructionsTitleTemplate: 'Comment utiliser {code} et les coupons',
    instructionsTemplates: [
      'Copiez le coupon promo actif (ex: {promoCode}).',
      'Copiez le code récompense {code}.',
      'Ouvrez YesStyle via notre lien officiel.',
      'Au paiement, saisissez le coupon promo dans Coupon Code.',
      'Saisissez {code} dans le champ séparé Reward Code.',
      'Vérifiez les deux réductions avant de payer.',
    ],
    emptyPromoInstructionsTemplates: [
      'Copiez le code récompense {code}.',
      'Ouvrez YesStyle via notre lien officiel et ajoutez vos produits.',
      'Au paiement, saisissez {code} dans le champ Reward Code.',
      'Si un coupon promo de la boutique est disponible, essayez de l’appliquer dans Coupon Code.',
      'Vérifiez le montant final avant de payer.',
    ],
    noteTemplate: 'Important : {code} va dans Reward Code, pas dans Coupon Code.',
    relatedContentTitle: 'Guides YesStyle',
    rewardArticleCardTitleTemplate: 'Guide du code {code}',
    rewardArticleCardSubtext: 'Pas à pas avec captures et conseils',
    guideCardTitle: 'Comment trouver des coupons valides',
    guideCardSubtext: 'Règles de cumul et livraison',
    faqTitle: 'Questions Fréquentes',
    faqs: [
      { question: 'Puis-je utiliser {code} avec un coupon ?', answer: 'Le code {code} dans le champ Reward Code peut être cumulé avec les coupons promo éligibles dans Coupon Code, sous réserve de confirmation au moment du paiement.' },
    ],
    transparencyTemplate: 'Cette page contient des liens affiliés. Si vous achetez via {code}, nous pouvons recevoir une commission sans frais supplémentaires.',
  },
  de: {
    locale: 'de',
    language: 'de-DE',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: 'Gutscheine',
    eyebrow: 'YesStyle Gutscheine & Reward Code',
    titleTemplate: 'YesStyle Reward Code {code}: Bis zu {newDiscount} % extra',
    descriptionTemplate: 'Offizieller YesStyle Reward Code {code}. Erhalte bis zu {newDiscount} % extra neben berechtigten Aktionsgutscheinen an der Kasse.',
    introTemplate: '{code} ist der offizielle YesStyle Reward Code. Gib ihn im Feld Reward Code ein, um bis zu {newDiscount} % extra ({newDiscount} % Erstbestellung / {returningDiscount} % Folgebestellungen) zu erhalten.',
    updated: 'Verifiziert',
    copy: 'Code kopieren',
    copied: 'Kopiert!',
    copyAriaTemplate: 'Code {code} kopieren',
    copyAriaPromoTemplate: 'Aktionsgutschein {promoCode} kopieren',
    visit: 'Zu YesStyle',
    rewardCardBadge: 'Reward Code (Aktiv)',
    rewardCardDescriptionTemplate: 'Aktiver Influencer-Code. Gib ihn im Feld Reward Code ein, um bis zu {newDiscount} % extra mit berechtigten Gutscheinen zu sparen.',
    rewardDiscountValueTemplate: 'Bis zu {newDiscount} % extra ({newDiscount} % Erstbestellung / {returningDiscount} % Folgebestellung)',
    promosSectionTitle: 'Verifizierte Aktionsgutscheine',
    emptyPromosNoticeTemplate: 'Derzeit keine verifizierten Aktionsgutscheine aktiv.',
    emptyPromosSubtextTemplate: 'Der Reward Code {code} bleibt im Feld Reward Code aktiv.',
    proofLabel: 'Offiziellen Nachweis anzeigen',
    validityUnconfirmed: 'Frist nicht angegeben',
    regionUnconfirmed: 'Region nicht angegeben',
    freeShippingLabel: 'Kostenloser Versand',
    tableHeaders: {
      type: 'Typ',
      code: 'Code',
      discount: 'Rabatt',
      validity: 'Gültigkeit',
      region: 'Region',
      verified: 'Verifiziert',
    },
    offerTypeReward: 'Reward Code',
    offerTypeCoupon: 'Aktionsgutschein',
    details: 'Code-Details',
    codeLabel: 'Code',
    discountLabel: 'Rabatt',
    discountValueTemplate: 'Bis zu {newDiscount} % extra ({newDiscount} % Erstbestellung / {returningDiscount} % Folgebestellung)',
    fieldLabel: 'Feld an der Kasse',
    fieldValue: 'Reward Code',
    instructionsTitleTemplate: 'So verwendest du {code} & Gutscheine',
    instructionsTemplates: [
      'Kopiere den aktiven Aktionsgutschein (z. B. {promoCode}).',
      'Kopiere den Reward Code {code}.',
      'Öffne YesStyle über unseren offiziellen Link.',
      'Gib den Aktionsgutschein im Feld Coupon Code ein.',
      'Gib {code} im separaten Feld Reward Code ein.',
      'Prüfe beide Rabatte vor dem Bezahlen.',
    ],
    emptyPromoInstructionsTemplates: [
      'Kopiere den Reward Code {code}.',
      'Öffne YesStyle über unseren offiziellen Link und lege Produkte in den Warenkorb.',
      'Gib {code} an der Kasse im Feld Reward Code ein.',
      'Falls ein Shop-Gutschein verfügbar ist, versuche ihn im Feld Coupon Code einzugeben.',
      'Prüfe den Endbetrag vor dem Bezahlen.',
    ],
    noteTemplate: 'Wichtig: {code} gehört in Reward Code, nicht in Coupon Code.',
    relatedContentTitle: 'YesStyle Ratgeber',
    rewardArticleCardTitleTemplate: 'Ratgeber zum Code {code}',
    rewardArticleCardSubtext: 'Schritt-für-Schritt mit Screenshots',
    guideCardTitle: 'Gültige Gutscheine finden',
    guideCardSubtext: 'Kombinationsregeln & Versand',
    faqTitle: 'Häufige Fragen',
    faqs: [
      { question: 'Kann ich {code} mit einem Gutschein nutzen?', answer: 'Der Code {code} im Feld Reward Code kann mit berechtigten Aktionsgutscheinen im Feld Coupon Code kombiniert werden. Die Ausweisung beider Rabatte ist an der Kasse zu prüfen.' },
    ],
    transparencyTemplate: 'Diese Seite enthält Affiliate-Links. Wenn du über {code} kaufst, erhalten wir möglicherweise eine Provision ohne Zusatzkosten.',
  },
  it: {
    locale: 'it',
    language: 'it-IT',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: 'Coupon',
    eyebrow: 'Coupon e Codice Ricompensa YesStyle',
    titleTemplate: 'Codice ricompensa YesStyle {code}: fino al {newDiscount}% in più',
    descriptionTemplate: 'Codice ricompensa ufficiale {code} su YesStyle: inseriscilo nel campo Reward Code per uno sconto extra fino al {newDiscount}%, cumulabile con i coupon promozionali idonei.',
    introTemplate: '{code} è il codice ricompensa ufficiale di YesStyle. Inseriscilo nel campo Reward Code per aggiungere fino al {newDiscount}% di sconto ({newDiscount}% sul primo ordine / {returningDiscount}% sugli ordini successivi) ai coupon promozionali attivi e idonei.',
    updated: 'Verificato',
    copy: 'Copia il codice',
    copied: 'Copiato!',
    copyAriaTemplate: 'Copia il codice {code}',
    copyAriaPromoTemplate: 'Copia il coupon promozionale {promoCode}',
    visit: 'Vai su YesStyle',
    rewardCardBadge: 'Codice Ricompensa (Attivo)',
    rewardCardDescriptionTemplate: 'Codice influencer attivo. Inseriscilo nel campo Reward Code per aggiungere fino al {newDiscount}% di sconto ai coupon promozionali idonei.',
    rewardDiscountValueTemplate: 'Fino al {newDiscount}% extra ({newDiscount}% primo ordine / {returningDiscount}% ordini successivi)',
    promosSectionTitle: 'Coupon Promozionali Verificati',
    emptyPromosNoticeTemplate: 'Al momento non ci sono coupon promozionali verificati.',
    emptyPromosSubtextTemplate: 'Il codice ricompensa {code} resta attivo nel campo Reward Code.',
    proofLabel: 'Vedi la prova ufficiale',
    validityUnconfirmed: 'Scadenza non indicata',
    regionUnconfirmed: 'Regione non indicata',
    freeShippingLabel: 'Spedizione Gratuita',
    tableHeaders: {
      type: 'Tipo',
      code: 'Codice',
      discount: 'Sconto',
      validity: 'Validità',
      region: 'Regione',
      verified: 'Verificato',
    },
    offerTypeReward: 'Codice Ricompensa',
    offerTypeCoupon: 'Coupon Promozionale',
    details: 'Dettagli del codice',
    codeLabel: 'Codice',
    discountLabel: 'Sconto',
    discountValueTemplate: 'Fino al {newDiscount}% extra ({newDiscount}% nuovi clienti / {returningDiscount}% clienti abituali)',
    fieldLabel: 'Campo al checkout',
    fieldValue: 'Reward Code',
    instructionsTitleTemplate: 'Come usare {code} e i coupon al checkout',
    instructionsTemplates: [
      'Copia il coupon promozionale attivo (es. {promoCode}).',
      'Copia il codice ricompensa {code}.',
      'Apri YesStyle dal link ufficiale di Cecília.',
      'Al checkout, incolla il coupon promozionale nel campo Coupon Code.',
      'Incolla {code} nel campo separato Reward Code.',
      'Controlla nel riepilogo dell’ordine che entrambi gli sconti siano applicati prima di pagare.',
    ],
    emptyPromoInstructionsTemplates: [
      'Copia il codice ricompensa {code}.',
      'Apri YesStyle dal link ufficiale di Cecília e aggiungi i tuoi prodotti.',
      'Al checkout, inserisci {code} nel campo Reward Code.',
      'Se c’è un coupon stagionale del negozio, prova ad applicarlo nel campo Coupon Code.',
      'Controlla l’importo finale e lo sconto applicato prima di pagare.',
    ],
    noteTemplate: 'Importante: {code} va nel campo Reward Code, i coupon promozionali in Coupon Code.',
    relatedContentTitle: 'Guide YesStyle',
    rewardArticleCardTitleTemplate: 'Guida al codice {code}',
    rewardArticleCardSubtext: 'Passo passo con schermate e consigli',
    guideCardTitle: 'Come trovare coupon validi',
    guideCardSubtext: 'Regole di cumulo e spedizione',
    faqTitle: 'Domande Frequenti',
    faqs: [
      { question: 'Posso usare {code} insieme a un coupon?', answer: 'Il codice {code} nel campo Reward Code si può cumulare con i coupon promozionali idonei nel campo Coupon Code. Controlla sempre nel riepilogo del checkout che entrambi gli sconti siano applicati.' },
    ],
    transparencyTemplate: 'Questa pagina contiene link di affiliazione. Se acquisti tramite il link o usi il codice {code}, potremmo ricevere una commissione senza costi aggiuntivi per te.',
  },
  ko: {
    locale: 'ko',
    language: 'ko-KR',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: '쿠폰',
    eyebrow: 'YesStyle 쿠폰 및 리워드 코드',
    titleTemplate: 'YesStyle 리워드 코드 {code}: 추가 {newDiscount}% 할인',
    descriptionTemplate: '공식 YesStyle 리워드 코드 {code}. 결제 시 대상 프로모션 쿠폰과 함께 최대 추가 {newDiscount}% 혜택을 받으세요.',
    introTemplate: '{code}은 공식 YesStyle 리워드 코드입니다. Reward Code 전용 칸에 입력하면 최대 추가 {newDiscount}% (첫 구매 {newDiscount}% / 재구매 {returningDiscount}%) 혜택을 받을 수 있습니다.',
    updated: '확인일',
    copy: '코드 복사',
    copied: '복사됨!',
    copyAriaTemplate: '코드 {code} 복사',
    copyAriaPromoTemplate: '프로모션 쿠폰 {promoCode} 복사',
    visit: 'YesStyle 방문',
    rewardCardBadge: '리워드 코드 (활성)',
    rewardCardDescriptionTemplate: '활성 인플루언서 리워드 코드. Reward Code 칸에 입력해 추가 {newDiscount}% 할인을 받으세요.',
    rewardDiscountValueTemplate: '최대 {newDiscount}% 추가 할인 (첫 구매 {newDiscount}% / 재구매 {returningDiscount}%)',
    promosSectionTitle: '검증된 프로모션 쿠폰',
    emptyPromosNoticeTemplate: '현재 검증된 프로모션 쿠폰이 없습니다.',
    emptyPromosSubtextTemplate: '리워드 코드 {code}은 Reward Code 칸에서 계속 활성화 상태입니다.',
    proofLabel: '공식 증빙 보기',
    validityUnconfirmed: '기한 미기재',
    regionUnconfirmed: '지역 미기재',
    freeShippingLabel: '무료 배송',
    tableHeaders: {
      type: '구분',
      code: '코드',
      discount: '할인율',
      validity: '유효기간',
      region: '적용지역',
      verified: '확인일',
    },
    offerTypeReward: '리워드 코드',
    offerTypeCoupon: '프로모션 쿠폰',
    details: '코드 정보',
    codeLabel: '코드',
    discountLabel: '할인율',
    discountValueTemplate: '최대 {newDiscount}% 추가 할인 (첫 구매 {newDiscount}% / 재구매 {returningDiscount}%)',
    fieldLabel: '결제 입력란',
    fieldValue: 'Reward Code',
    instructionsTitleTemplate: '{code} 및 쿠폰 사용 방법',
    instructionsTemplates: [
      '활성 프로모션 쿠폰(예: {promoCode})을 복사하세요.',
      '리워드 코드 {code}을 복사하세요.',
      '공식 링크를 통해 YesStyle에 접속하세요.',
      '결제 시 Coupon Code 칸에 프로모션 쿠폰을 입력하세요.',
      '별도의 Reward Code 칸에 {code}을 입력하세요.',
      '결제 전 두 할인 모두 적용되었는지 확인하세요.',
    ],
    emptyPromoInstructionsTemplates: [
      '리워드 코드 {code}을 복사하세요.',
      '공식 링크를 통해 YesStyle에 접속하고 상품을 담으세요.',
      '결제 시 Reward Code 칸에 {code}을 입력하세요.',
      '쇼핑몰 프로모션 쿠폰이 있다면 Coupon Code 칸에 적용해 보세요.',
      '결제 전 최종 할인 금액을 확인하세요.',
    ],
    noteTemplate: '중요: {code}은 Coupon Code가 아닌 Reward Code에 입력하세요.',
    relatedContentTitle: 'YesStyle 가이드',
    rewardArticleCardTitleTemplate: '{code} 코드 사용 가이드',
    rewardArticleCardSubtext: '스크린샷과 함께하는 단계별 가이드',
    guideCardTitle: '유효한 쿠폰 찾는 방법',
    guideCardSubtext: '중복 적용 규칙 및 배송',
    faqTitle: '자주 묻는 질문',
    faqs: [
      { question: '{code} 코드를 다른 쿠폰과 함께 사용할 수 있나요?', answer: 'Reward Code 칸의 {code} 코드는 Coupon Code 칸의 대상 프로모션 쿠폰과 함께 적용될 수 있으며, 최종 적용 여부는 결제 요약 화면에서 확인해야 합니다.' },
    ],
    transparencyTemplate: '이 페이지에는 제휴 링크가 포함되어 있습니다. 코드를 사용하여 구매 시 수수료를 지급받을 수 있습니다.',
  },
  ja: {
    locale: 'ja',
    language: 'ja-JP',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: 'クーポン',
    eyebrow: 'YesStyle クーポン＆リワードコード',
    titleTemplate: 'YesStyle リワードコード {code}：さらに{newDiscount}%オフ',
    descriptionTemplate: 'YesStyle公式リワードコード{code}。チェックアウト時に対象のプロモーションクーポンと併用して最大{newDiscount}%追加オフ。',
    introTemplate: '{code}は公式YesStyleリワードコードです。Reward Code欄に入力すると最大で追加{newDiscount}%（初回{newDiscount}% / 2回目以降{returningDiscount}%）の特典が適用されます。',
    updated: '確認日',
    copy: 'コードをコピー',
    copied: 'コピーしました！',
    copyAriaTemplate: 'コード {code} をコピー',
    copyAriaPromoTemplate: 'クーポンコード {promoCode} をコピー',
    visit: 'YesStyleへ',
    rewardCardBadge: 'リワードコード（有効）',
    rewardCardDescriptionTemplate: '有効なインフルエンサーコード。Reward Code欄に入力して追加割引を適用してください。',
    rewardDiscountValueTemplate: '最大{newDiscount}%追加オフ（初回{newDiscount}% / 2回目以降{returningDiscount}%）',
    promosSectionTitle: '検証済みプロモーションクーポン',
    emptyPromosNoticeTemplate: '現在、検証済みのプロモーションクーポンはありません。',
    emptyPromosSubtextTemplate: 'リワードコード {code} は Reward Code 欄で引き続き有効です。',
    proofLabel: '公式証明を見る',
    validityUnconfirmed: '期限未記載',
    regionUnconfirmed: '地域未記載',
    freeShippingLabel: '送料無料',
    tableHeaders: {
      type: '種別',
      code: 'コード',
      discount: '割引率',
      validity: '有効期限',
      region: '対象地域',
      verified: '確認日',
    },
    offerTypeReward: 'リワードコード',
    offerTypeCoupon: 'プロモクーポン',
    details: 'コードの詳細',
    codeLabel: 'コード',
    discountLabel: '割引率',
    discountValueTemplate: '最大{newDiscount}%追加オフ（初回{newDiscount}% / 2回目以降{returningDiscount}%）',
    fieldLabel: '入力欄',
    fieldValue: 'Reward Code',
    instructionsTitleTemplate: '{code} とクーポンの使い方',
    instructionsTemplates: [
      '有効なプロモーションクーポン（例：{promoCode}）をコピーします。',
      'リワードコード {code} をコピーします。',
      '公式リンクから YesStyle にアクセスします。',
      'チェックアウト時に Coupon Code 欄へプロモクーポンを入力します。',
      '別欄の Reward Code 欄へ {code} を入力します。',
      '注文前に両方の割引を確認します。',
    ],
    emptyPromoInstructionsTemplates: [
      'リワードコード {code} をコピーします。',
      '公式リンクから YesStyle にアクセスし、商品をカートに入れます。',
      'チェックアウト時に Reward Code 欄へ {code} を入力します。',
      'ショップクーポンがある場合は Coupon Code 欄への入力をお試しください。',
      '注文確定前に最終金額を確認します。',
    ],
    noteTemplate: '重要：{code}はCoupon CodeではなくReward Codeに入力してください。',
    relatedContentTitle: 'YesStyle ガイド',
    rewardArticleCardTitleTemplate: '{code} コードの使い方ガイド',
    rewardArticleCardSubtext: 'スクリーンショット付きのステップ解説',
    guideCardTitle: '有効なクーポンの探し方',
    guideCardSubtext: '併用ルールと送料について',
    faqTitle: 'よくある質問',
    faqs: [
      { question: '{code}はほかのクーポンと併用できますか？', answer: 'Reward Code 欄の {code} は対象のプロモーションクーポンと併用できる場合があります。両方の割引が適用されるかは注文確定前のチェックアウト画面で確認してください。' },
    ],
    transparencyTemplate: 'このページにはアフィリエイトリンクが含まれる場合があります。{code}を利用して購入すると報酬を得ることがあります。',
  },
  'zh-hant': {
    locale: 'zh-hant',
    language: 'zh-HK',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: '優惠碼',
    eyebrow: 'YesStyle 優惠碼與獎勵碼',
    titleTemplate: 'YesStyle 獎勵碼 {code}：額外 {newDiscount}% 優惠',
    descriptionTemplate: 'YesStyle 官方獎勵碼 {code}。在結帳時可與適用促銷優惠碼組合使用，額外享有最高 {newDiscount}% 優惠。',
    introTemplate: '{code} 是 YesStyle 官方獎勵碼。請在 Reward Code 專用欄位輸入，即可獲得最高額外 {newDiscount}% 優惠（首購 {newDiscount}% / 複購 {returningDiscount}%）。',
    updated: '已驗證',
    copy: '複製優惠碼',
    copied: '已複製！',
    copyAriaTemplate: '複製優惠碼 {code}',
    copyAriaPromoTemplate: '複製促銷優惠碼 {promoCode}',
    visit: '前往 YesStyle',
    rewardCardBadge: '獎勵碼（有效）',
    rewardCardDescriptionTemplate: '有效網紅獎勵碼。在 Reward Code 欄位輸入，即可享額外最高 {newDiscount}% 折扣。',
    rewardDiscountValueTemplate: '最高額外 {newDiscount}% 優惠（首購 {newDiscount}% / 複購 {returningDiscount}%）',
    promosSectionTitle: '已驗證促銷優惠碼',
    emptyPromosNoticeTemplate: '目前沒有已驗證的促銷優惠碼。',
    emptyPromosSubtextTemplate: '獎勵碼 {code} 在 Reward Code 欄位仍保持有效。',
    proofLabel: '查看官方證明',
    validityUnconfirmed: '未註明期限',
    regionUnconfirmed: '未註明地區',
    freeShippingLabel: '免運費',
    tableHeaders: {
      type: '類型',
      code: '優惠碼',
      discount: '折扣',
      validity: '有效期限',
      region: '適用地區',
      verified: '驗證日',
    },
    offerTypeReward: '獎勵碼',
    offerTypeCoupon: '促銷優惠碼',
    details: '優惠碼詳情',
    codeLabel: '優惠碼',
    discountLabel: '折扣力度',
    discountValueTemplate: '最高額外 {newDiscount}% 優惠（首購 {newDiscount}% / 複購 {returningDiscount}%）',
    fieldLabel: '輸入欄位',
    fieldValue: 'Reward Code',
    instructionsTitleTemplate: '如何組合使用 {code} 與優惠碼',
    instructionsTemplates: [
      '複製有效的促銷優惠碼（例如 {promoCode}）。',
      '複製獎勵碼 {code}。',
      '透過官方連結前往 YesStyle。',
      '結帳時在 Coupon Code 欄位輸入促銷優惠碼。',
      '在獨立的 Reward Code 欄位輸入 {code}。',
      '付款前確認兩項優惠皆已套用。',
    ],
    emptyPromoInstructionsTemplates: [
      '複製獎勵碼 {code}。',
      '透過官方連結前往 YesStyle 並選購商品。',
      '結帳時在 Reward Code 欄位輸入 {code}。',
      '如有店家優惠碼，可嘗試於 Coupon Code 欄位輸入。',
      '付款前確認最終折扣與金額。',
    ],
    noteTemplate: '重要：{code} 應輸入 Reward Code，而不是 Coupon Code。',
    relatedContentTitle: 'YesStyle 指南',
    rewardArticleCardTitleTemplate: '{code} 優惠碼使用指南',
    rewardArticleCardSubtext: '附螢幕截圖的圖文教學',
    guideCardTitle: '如何尋找有效優惠碼',
    guideCardSubtext: '疊加規則與免運條件',
    faqTitle: '常見問題',
    faqs: [
      { question: '{code} 可以與其他優惠碼同時使用嗎？', answer: 'Reward Code 欄位的 {code} 可與 Coupon Code 欄位的適用促銷優惠碼組合使用，實際疊加結果須以結帳明細為準。' },
    ],
    transparencyTemplate: '此頁面包含聯盟連結。使用 {code} 購物時，我們可能會獲得佣金。',
  },
  'zh-hans': {
    locale: 'zh-hans',
    language: 'zh-CN',
    homeLabel: 'Em Casa com Cecília',
    couponsLabel: '优惠码',
    eyebrow: 'YesStyle 优惠码与奖励码',
    titleTemplate: 'YesStyle 奖励码 {code}：额外 {newDiscount}% 优惠',
    descriptionTemplate: 'YesStyle 官方奖励码 {code}。在结账时可与适用促销优惠码组合使用，额外享受最高 {newDiscount}% 优惠。',
    introTemplate: '{code} 是 YesStyle 官方奖励码。请在 Reward Code 专用栏位输入，即可获得最高额外 {newDiscount}% 优惠（首购 {newDiscount}% / 复购 {returningDiscount}%）。',
    updated: '已验证',
    copy: '复制优惠码',
    copied: '已复制！',
    copyAriaTemplate: '复制优惠码 {code}',
    copyAriaPromoTemplate: '复制促销优惠码 {promoCode}',
    visit: '前往 YesStyle',
    rewardCardBadge: '奖励码（有效）',
    rewardCardDescriptionTemplate: '有效网红奖励码。在 Reward Code 栏位输入，即可享额外最高 {newDiscount}% 折扣。',
    rewardDiscountValueTemplate: '最高额外 {newDiscount}% 优惠（首购 {newDiscount}% / 复购 {returningDiscount}%）',
    promosSectionTitle: '已验证促销优惠码',
    emptyPromosNoticeTemplate: '目前没有已验证的促销优惠码。',
    emptyPromosSubtextTemplate: '奖励码 {code} 在 Reward Code 栏位仍保持有效。',
    proofLabel: '查看官方证明',
    validityUnconfirmed: '未注明期限',
    regionUnconfirmed: '未注明地区',
    freeShippingLabel: '免运费',
    tableHeaders: {
      type: '类型',
      code: '优惠码',
      discount: '折扣',
      validity: '有效期限',
      region: '适用地区',
      verified: '验证日',
    },
    offerTypeReward: '奖励码',
    offerTypeCoupon: '促销优惠码',
    details: '优惠码详情',
    codeLabel: '优惠码',
    discountLabel: '折扣力度',
    discountValueTemplate: '最高额外 {newDiscount}% 优惠（首购 {newDiscount}% / 复购 {returningDiscount}%）',
    fieldLabel: '输入栏位',
    fieldValue: 'Reward Code',
    instructionsTitleTemplate: '如何组合使用 {code} 与优惠码',
    instructionsTemplates: [
      '复制有效的促销优惠码（例如 {promoCode}）。',
      '复制奖励码 {code}。',
      '通过官方链接前往 YesStyle。',
      '结账时在 Coupon Code 栏位输入促销优惠码。',
      '在独立的 Reward Code 栏位输入 {code}。',
      '付款前确认两项优惠均已应用。',
    ],
    emptyPromoInstructionsTemplates: [
      '复制奖励码 {code}。',
      '通过官方链接前往 YesStyle 并选购商品。',
      '结账时在 Reward Code 栏位输入 {code}。',
      '如有店家优惠码，可尝试于 Coupon Code 栏位输入。',
      '付款前确认最终折扣与金额。',
    ],
    noteTemplate: '重要：{code} 应输入 Reward Code，而不是 Coupon Code。',
    relatedContentTitle: 'YesStyle 指南',
    rewardArticleCardTitleTemplate: '{code} 优惠码使用指南',
    rewardArticleCardSubtext: '附屏幕截图的图文教学',
    guideCardTitle: '如何寻找有效优惠码',
    guideCardSubtext: '叠加规则与免运条件',
    faqTitle: '常见问题',
    faqs: [
      { question: '{code} 可以和其他优惠码一起使用吗？', answer: 'Reward Code 栏位的 {code} 可与 Coupon Code 栏位的适用促销优惠码组合使用，实际叠加结果须以结账明细为準。' },
    ],
    transparencyTemplate: '此页面包含联盟链接。使用 {code} 购物时，我们可能会获得佣金。',
  },
};

export const yesStyleLocales = Object.keys(pages) as Locale[];

export function getYesStylePage(locale: string): PageCopy | null {
  return pages[locale as Locale] || null;
}
